[package]
name = "smart-shift-eco"
description = "ADLX Rust sample: query AMD SmartShift Eco settings"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "SmartShiftEco"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
