var _d_o_x__i_a_d_l_x_g_p_u_metrics_support =
[
    [ "GetGPUClockSpeedRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_clock_speed_range.html", null ],
    [ "GetGPUFanSpeedRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_fan_speed_range.html", null ],
    [ "GetGPUHotspotTemperatureRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_hotspot_temperature_range.html", null ],
    [ "GetGPUIntakeTemperatureRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_intake_temperature_range.html", null ],
    [ "GetGPUPowerRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_power_range.html", null ],
    [ "GetGPUTemperatureRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_temperature_range.html", null ],
    [ "GetGPUTotalBoardPowerRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_total_board_power_range.html", null ],
    [ "GetGPUUsageRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_usage_range.html", null ],
    [ "GetGPUVRAMClockSpeedRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_v_r_a_m_clock_speed_range.html", null ],
    [ "GetGPUVRAMRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_v_r_a_m_range.html", null ],
    [ "GetGPUVoltageRange", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__get_g_p_u_voltage_range.html", null ],
    [ "IsSupportedGPUClockSpeed", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_clock_speed.html", null ],
    [ "IsSupportedGPUFanSpeed", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_fan_speed.html", null ],
    [ "IsSupportedGPUHotspotTemperature", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_hotspot_temperature.html", null ],
    [ "IsSupportedGPUIntakeTemperature", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_intake_temperature.html", null ],
    [ "IsSupportedGPUPower", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_power.html", null ],
    [ "IsSupportedGPUTemperature", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_temperature.html", null ],
    [ "IsSupportedGPUTotalBoardPower", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_total_board_power.html", null ],
    [ "IsSupportedGPUUsage", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_usage.html", null ],
    [ "IsSupportedGPUVRAM", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_v_r_a_m.html", null ],
    [ "IsSupportedGPUVRAMClockSpeed", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_v_r_a_m_clock_speed.html", null ],
    [ "IsSupportedGPUVoltage", "_d_o_x__i_a_d_l_x_g_p_u_metrics_support__is_supported_g_p_u_voltage.html", null ]
];