var _d_o_x__i_a_d_l_x_display_gamma =
[
    [ "GetGammaCoefficient", "_d_o_x__i_a_d_l_x_display_gamma__get_gamma_coefficient.html", null ],
    [ "GetGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__get_gamma_ramp.html", null ],
    [ "IsCurrentDeGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__is_current_de_gamma_ramp.html", null ],
    [ "IsCurrentReGamma36", "_d_o_x__i_a_d_l_x_display_gamma__is_current_re_gamma36.html", null ],
    [ "IsCurrentReGammaBT709", "_d_o_x__i_a_d_l_x_display_gamma__is_current_re_gamma_b_t709.html", null ],
    [ "IsCurrentReGammaPQ", "_d_o_x__i_a_d_l_x_display_gamma__is_current_re_gamma_p_q.html", null ],
    [ "IsCurrentReGammaPQ2084Interim", "_d_o_x__i_a_d_l_x_display_gamma__is_current_re_gamma_p_q2084_interim.html", null ],
    [ "IsCurrentReGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__is_current_re_gamma_ramp.html", null ],
    [ "IsCurrentReGammaSRGB", "_d_o_x__i_a_d_l_x_display_gamma__is_current_re_gamma_s_r_g_b.html", null ],
    [ "IsCurrentRegammaCoefficient", "_d_o_x__i_a_d_l_x_display_gamma__is_current_regamma_coefficient.html", null ],
    [ "IsSupportedReGamma36", "_d_o_x__i_a_d_l_x_display_gamma__is_supported_re_gamma36.html", null ],
    [ "IsSupportedReGammaBT709", "_d_o_x__i_a_d_l_x_display_gamma__is_supported_re_gamma_b_t709.html", null ],
    [ "IsSupportedReGammaPQ", "_d_o_x__i_a_d_l_x_display_gamma__is_supported_re_gamma_p_q.html", null ],
    [ "IsSupportedReGammaPQ2084Interim", "_d_o_x__i_a_d_l_x_display_gamma__is_supported_re_gamma_p_q2084_interim.html", null ],
    [ "IsSupportedReGammaSRGB", "_d_o_x__i_a_d_l_x_display_gamma__is_supported_re_gamma_s_r_g_b.html", null ],
    [ "ResetGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__reset_gamma_ramp.html", null ],
    [ "SetDeGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__set_de_gamma_ramp_file.html", null ],
    [ "SetDeGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__set_de_gamma_ramp_memory.html", null ],
    [ "SetReGamma36", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma36.html", null ],
    [ "SetReGammaBT709", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_b_t709.html", null ],
    [ "SetReGammaCoefficient", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_coefficient.html", null ],
    [ "SetReGammaPQ", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_p_q.html", null ],
    [ "SetReGammaPQ2084Interim", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_p_q2084_interim.html", null ],
    [ "SetReGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_ramp_file.html", null ],
    [ "SetReGammaRamp", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_ramp_memory.html", null ],
    [ "SetReGammaSRGB", "_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_s_r_g_b.html", null ]
];