var _d_o_x__i_a_d_l_x_display_gamut =
[
    [ "GetGamutColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__get_gamut_color_space.html", null ],
    [ "GetWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__get_white_point.html", null ],
    [ "IsCurrent5000kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_current5000k_white_point.html", null ],
    [ "IsCurrent6500kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_current6500k_white_point.html", null ],
    [ "IsCurrent7500kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_current7500k_white_point.html", null ],
    [ "IsCurrent9300kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_current9300k_white_point.html", null ],
    [ "IsCurrentAdobeRgbColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_current_adobe_rgb_color_space.html", null ],
    [ "IsCurrentCCIR2020ColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_current_c_c_i_r2020_color_space.html", null ],
    [ "IsCurrentCCIR601ColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_current_c_c_i_r601_color_space.html", null ],
    [ "IsCurrentCCIR709ColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_current_c_c_i_r709_color_space.html", null ],
    [ "IsCurrentCIERgbColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_current_c_i_e_rgb_color_space.html", null ],
    [ "IsCurrentCustomColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_current_custom_color_space.html", null ],
    [ "IsCurrentCustomWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_current_custom_white_point.html", null ],
    [ "IsSupported5000kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_supported5000k_white_point.html", null ],
    [ "IsSupported6500kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_supported6500k_white_point.html", null ],
    [ "IsSupported7500kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_supported7500k_white_point.html", null ],
    [ "IsSupported9300kWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_supported9300k_white_point.html", null ],
    [ "IsSupportedAdobeRgbColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_adobe_rgb_color_space.html", null ],
    [ "IsSupportedCCIR2020ColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_c_c_i_r2020_color_space.html", null ],
    [ "IsSupportedCCIR601ColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_c_c_i_r601_color_space.html", null ],
    [ "IsSupportedCCIR709ColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_c_c_i_r709_color_space.html", null ],
    [ "IsSupportedCIERgbColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_c_i_e_rgb_color_space.html", null ],
    [ "IsSupportedCustomColorSpace", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_custom_color_space.html", null ],
    [ "IsSupportedCustomWhitePoint", "_d_o_x__i_a_d_l_x_display_gamut__is_supported_custom_white_point.html", null ],
    [ "SetGamut", "_d_o_x__i_a_d_l_x_display_gamut__set_gamut__c_w__c_g.html", null ],
    [ "SetGamut", "_d_o_x__i_a_d_l_x_display_gamut__set_gamut__c_w__p_g.html", null ],
    [ "SetGamut", "_d_o_x__i_a_d_l_x_display_gamut__set_gamut__p_w__c_g.html", null ],
    [ "SetGamut", "_d_o_x__i_a_d_l_x_display_gamut__set_gamut__p_w__p_g.html", null ]
];