var display =
[
    [ "IADLXBlueLightReduction", "_d_o_x__i_a_d_l_x_blue_light_reduction.html", "_d_o_x__i_a_d_l_x_blue_light_reduction" ],
    [ "IADLXDisplay", "_d_o_x__i_a_d_l_x_display.html", "_d_o_x__i_a_d_l_x_display" ],
    [ "IADLXDisplay3DLUT", "_d_o_x__i_a_d_l_x_display3_d_l_u_t.html", "_d_o_x__i_a_d_l_x_display3_d_l_u_t" ],
    [ "IADLXDisplay3DLUTChangedEvent", "_d_o_x__i_a_d_l_x_display3_d_l_u_t_changed_event.html", "_d_o_x__i_a_d_l_x_display3_d_l_u_t_changed_event" ],
    [ "IADLXDisplay3DLUTChangedListener", "_d_o_x__i_a_d_l_x_display3_d_l_u_t_changed_listener.html", "_d_o_x__i_a_d_l_x_display3_d_l_u_t_changed_listener" ],
    [ "IADLXDisplayBlanking", "_d_o_x__i_a_d_l_x_display_blanking.html", "_d_o_x__i_a_d_l_x_display_blanking" ],
    [ "IADLXDisplayChangedHandling", "_d_o_x__i_a_d_l_x_display_changed_handling.html", "_d_o_x__i_a_d_l_x_display_changed_handling" ],
    [ "IADLXDisplayColorDepth", "_d_o_x__i_a_d_l_x_display_color_depth.html", "_d_o_x__i_a_d_l_x_display_color_depth" ],
    [ "IADLXDisplayCustomColor", "_d_o_x__i_a_d_l_x_display_custom_color.html", "_d_o_x__i_a_d_l_x_display_custom_color" ],
    [ "IADLXDisplayCustomResolution", "_d_o_x__i_a_d_l_x_display_custom_resolution.html", "_d_o_x__i_a_d_l_x_display_custom_resolution" ],
    [ "IADLXDisplayFreeSync", "_d_o_x__i_a_d_l_x_display_free_sync.html", "_d_o_x__i_a_d_l_x_display_free_sync" ],
    [ "IADLXDisplayGPUScaling", "_d_o_x__i_a_d_l_x_display_g_p_u_scaling.html", "_d_o_x__i_a_d_l_x_display_g_p_u_scaling" ],
    [ "IADLXDisplayGamma", "_d_o_x__i_a_d_l_x_display_gamma.html", "_d_o_x__i_a_d_l_x_display_gamma" ],
    [ "IADLXDisplayGammaChangedEvent", "_d_o_x__i_a_d_l_x_display_gamma_changed_event.html", "_d_o_x__i_a_d_l_x_display_gamma_changed_event" ],
    [ "IADLXDisplayGammaChangedListener", "_d_o_x__i_a_d_l_x_display_gamma_changed_listener.html", "_d_o_x__i_a_d_l_x_display_gamma_changed_listener" ],
    [ "IADLXDisplayGamut", "_d_o_x__i_a_d_l_x_display_gamut.html", "_d_o_x__i_a_d_l_x_display_gamut" ],
    [ "IADLXDisplayGamutChangedEvent", "_d_o_x__i_a_d_l_x_display_gamut_changed_event.html", "_d_o_x__i_a_d_l_x_display_gamut_changed_event" ],
    [ "IADLXDisplayGamutChangedListener", "_d_o_x__i_a_d_l_x_display_gamut_changed_listener.html", "_d_o_x__i_a_d_l_x_display_gamut_changed_listener" ],
    [ "IADLXDisplayHDCP", "_d_o_x__i_a_d_l_x_display_h_d_c_p.html", "_d_o_x__i_a_d_l_x_display_h_d_c_p" ],
    [ "IADLXDisplayIntegerScaling", "_d_o_x__i_a_d_l_x_display_integer_scaling.html", "_d_o_x__i_a_d_l_x_display_integer_scaling" ],
    [ "IADLXDisplayList", "_d_o_x__i_a_d_l_x_display_list.html", "_d_o_x__i_a_d_l_x_display_list" ],
    [ "IADLXDisplayListChangedListener", "_d_o_x__i_a_d_l_x_display_list_changed_listener.html", "_d_o_x__i_a_d_l_x_display_list_changed_listener" ],
    [ "IADLXDisplayPixelFormat", "_d_o_x__i_a_d_l_x_display_pixel_format.html", "_d_o_x__i_a_d_l_x_display_pixel_format" ],
    [ "IADLXDisplayResolution", "_d_o_x__i_a_d_l_x_display_resolution.html", "_d_o_x__i_a_d_l_x_display_resolution" ],
    [ "IADLXDisplayResolutionList", "_d_o_x__i_a_d_l_x_display_resolution_list.html", "_d_o_x__i_a_d_l_x_display_resolution_list" ],
    [ "IADLXDisplayScalingMode", "_d_o_x__i_a_d_l_x_display_scaling_mode.html", "_d_o_x__i_a_d_l_x_display_scaling_mode" ],
    [ "IADLXDisplayServices", "_d_o_x__i_a_d_l_x_display_services.html", "_d_o_x__i_a_d_l_x_display_services" ],
    [ "IADLXDisplayServices1", "_d_o_x__i_a_d_l_x_display_services1.html", "_d_o_x__i_a_d_l_x_display_services1" ],
    [ "IADLXDisplaySettingsChangedEvent", "_d_o_x__i_a_d_l_x_display_settings_changed_event.html", "_d_o_x__i_a_d_l_x_display_settings_changed_event" ],
    [ "IADLXDisplaySettingsChangedEvent1", "_d_o_x__i_a_d_l_x_display_settings_changed_event1.html", "_d_o_x__i_a_d_l_x_display_settings_changed_event1" ],
    [ "IADLXDisplaySettingsChangedListener", "_d_o_x__i_a_d_l_x_display_settings_changed_listener.html", "_d_o_x__i_a_d_l_x_display_settings_changed_listener" ],
    [ "IADLXDisplayVSR", "_d_o_x__i_a_d_l_x_display_v_s_r.html", "_d_o_x__i_a_d_l_x_display_v_s_r" ],
    [ "IADLXDisplayVariBright", "_d_o_x__i_a_d_l_x_display_vari_bright.html", "_d_o_x__i_a_d_l_x_display_vari_bright" ]
];