var gfx3dgraphics =
[
    [ "IADLX3DAMDFluidMotionFrames", "_d_o_x__i_a_d_l_x3_d_a_m_d_fluid_motion_frames.html", "_d_o_x__i_a_d_l_x3_d_a_m_d_fluid_motion_frames" ],
    [ "IADLX3DAnisotropicFiltering", "_d_o_x__i_a_d_l_x3_d_anisotropic_filtering.html", "_d_o_x__i_a_d_l_x3_d_anisotropic_filtering" ],
    [ "IADLX3DAntiAliasing", "_d_o_x__i_a_d_l_x3_d_anti_aliasing.html", "_d_o_x__i_a_d_l_x3_d_anti_aliasing" ],
    [ "IADLX3DAntiLag", "_d_o_x__i_a_d_l_x3_d_anti_lag.html", "_d_o_x__i_a_d_l_x3_d_anti_lag" ],
    [ "IADLX3DAntiLag1", "_d_o_x__i_a_d_l_x3_d_anti_lag1.html", "_d_o_x__i_a_d_l_x3_d_anti_lag1" ],
    [ "IADLX3DBoost", "_d_o_x__i_a_d_l_x3_d_boost.html", "_d_o_x__i_a_d_l_x3_d_boost" ],
    [ "IADLX3DChill", "_d_o_x__i_a_d_l_x3_d_chill.html", "_d_o_x__i_a_d_l_x3_d_chill" ],
    [ "IADLX3DEnhancedSync", "_d_o_x__i_a_d_l_x3_d_enhanced_sync.html", "_d_o_x__i_a_d_l_x3_d_enhanced_sync" ],
    [ "IADLX3DFrameRateTargetControl", "_d_o_x__i_a_d_l_x3_d_frame_rate_target_control.html", "_d_o_x__i_a_d_l_x3_d_frame_rate_target_control" ],
    [ "IADLX3DImageSharpening", "_d_o_x__i_a_d_l_x3_d_image_sharpening.html", "_d_o_x__i_a_d_l_x3_d_image_sharpening" ],
    [ "IADLX3DImageSharpenDesktop", "_d_o_x__i_a_d_l_x3_d_image_sharpen_desktop.html", "_d_o_x__i_a_d_l_x3_d_image_sharpen_desktop" ],
    [ "IADLX3DMorphologicalAntiAliasing", "_d_o_x__i_a_d_l_x3_d_morphological_anti_aliasing.html", "_d_o_x__i_a_d_l_x3_d_morphological_anti_aliasing" ],
    [ "IADLX3DRadeonSuperResolution", "_d_o_x__i_a_d_l_x3_d_radeon_super_resolution.html", "_d_o_x__i_a_d_l_x3_d_radeon_super_resolution" ],
    [ "IADLX3DResetShaderCache", "_d_o_x__i_a_d_l_x3_d_reset_shader_cache.html", "_d_o_x__i_a_d_l_x3_d_reset_shader_cache" ],
    [ "IADLX3DSettingsChangedEvent", "_d_o_x__i_a_d_l_x3_d_settings_changed_event.html", "_d_o_x__i_a_d_l_x3_d_settings_changed_event" ],
    [ "IADLX3DSettingsChangedEvent1", "_d_o_x__i_a_d_l_x3_d_settings_changed_event1.html", "_d_o_x__i_a_d_l_x3_d_settings_changed_event1" ],
    [ "IADLX3DSettingsChangedEvent2", "_d_o_x__i_a_d_l_x3_d_settings_changed_event2.html", "_d_o_x__i_a_d_l_x3_d_settings_changed_event2" ],
    [ "IADLX3DSettingsChangedHandling", "_d_o_x__i_a_d_l_x3_d_settings_changed_handling.html", "_d_o_x__i_a_d_l_x3_d_settings_changed_handling" ],
    [ "IADLX3DSettingsChangedListener", "_d_o_x__i_a_d_l_x3_d_settings_changed_listener.html", "_d_o_x__i_a_d_l_x3_d_settings_changed_listener" ],
    [ "IADLX3DSettingsServices", "_d_o_x__i_a_d_l_x3_d_settings_services.html", "_d_o_x__i_a_d_l_x3_d_settings_services" ],
    [ "IADLX3DSettingsServices1", "_d_o_x__i_a_d_l_x3_d_settings_services1.html", "_d_o_x__i_a_d_l_x3_d_settings_services1" ],
    [ "IADLX3DSettingsServices2", "_d_o_x__i_a_d_l_x3_d_settings_services2.html", "_d_o_x__i_a_d_l_x3_d_settings_services2" ],
    [ "IADLX3DTessellation", "_d_o_x__i_a_d_l_x3_d_tessellation.html", "_d_o_x__i_a_d_l_x3_d_tessellation" ],
    [ "IADLX3DWaitForVerticalRefresh", "_d_o_x__i_a_d_l_x3_d_wait_for_vertical_refresh.html", "_d_o_x__i_a_d_l_x3_d_wait_for_vertical_refresh" ]
];