[package]
name = "sync-multimedia"
description = "ADLX Rust sample: receive synchronous multimedia change notifications"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "SyncMultimedia"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
