var searchData=
[
  ['on3dsettingschanged_0',['On3DSettingsChanged',['../_d_o_x__i_a_d_l_x3_d_settings_changed_listener__on3_d_settings_changed.html',1,'DOX_IADLX3DSettingsChangedListener']]],
  ['ondesktoplistchanged_1',['OnDesktopListChanged',['../_d_o_x__i_a_d_l_x_desktop_list_changed_listener__on_desktop_list_changed.html',1,'DOX_IADLXDesktopListChangedListener']]],
  ['ondisplay3dlutchanged_2',['OnDisplay3DLUTChanged',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t_changed_listener__on_display3_d_l_u_t_changed.html',1,'DOX_IADLXDisplay3DLUTChangedListener']]],
  ['ondisplaygammachanged_3',['OnDisplayGammaChanged',['../_d_o_x__i_a_d_l_x_display_gamma_changed_listener__on_display_gamma_changed.html',1,'DOX_IADLXDisplayGammaChangedListener']]],
  ['ondisplaygamutchanged_4',['OnDisplayGamutChanged',['../_d_o_x__i_a_d_l_x_display_gamut_changed_listener__on_display_gamut_changed.html',1,'DOX_IADLXDisplayGamutChangedListener']]],
  ['ondisplaylistchanged_5',['OnDisplayListChanged',['../_d_o_x__i_a_d_l_x_display_list_changed_listener__on_display_list_changed.html',1,'DOX_IADLXDisplayListChangedListener']]],
  ['ondisplaysettingschanged_6',['OnDisplaySettingsChanged',['../_d_o_x__i_a_d_l_x_display_settings_changed_listener__on_display_settings_changed.html',1,'DOX_IADLXDisplaySettingsChangedListener']]],
  ['ongpuappslistchanged_7',['OnGPUAppsListChanged',['../_d_o_x__i_a_d_l_x_g_p_u_apps_list_event_listener__on_g_p_u_apps_list_changed.html',1,'DOX_IADLXGPUAppsListEventListener']]],
  ['ongpuautotuningcomplete_8',['OnGPUAutoTuningComplete',['../_d_o_x__i_a_d_l_x_g_p_u_auto_tuning_complete_listener__on_g_p_u_auto_tuning_complete.html',1,'DOX_IADLXGPUAutoTuningCompleteListener']]],
  ['ongpuconnectchanged_9',['OnGPUConnectChanged',['../_d_o_x__i_a_d_l_x_g_p_u_connect_changed_listener__on_g_p_u_connect_changed.html',1,'DOX_IADLXGPUConnectChangedListener']]],
  ['ongpulistchanged_10',['OnGPUListChanged',['../_d_o_x__i_a_d_l_x_g_p_us_event_listener__on_g_p_u_list_changed.html',1,'DOX_IADLXGPUsEventListener']]],
  ['ongpustresstestfinished_11',['OnGPUStressTestFinished',['../_d_o_x__i_a_d_l_x_g_p_u_stress_test_finished_listener__on_g_p_u_stress_test_finished.html',1,'DOX_IADLXGPUStressTestFinishedListener']]],
  ['ongputuningchanged_12',['OnGPUTuningChanged',['../_d_o_x__i_a_d_l_x_g_p_u_tuning_changed_listener__on_g_p_u_tuning_changed.html',1,'DOX_IADLXGPUTuningChangedListener']]],
  ['onmultimediachanged_13',['OnMultimediaChanged',['../_d_o_x__i_a_d_l_x_multimedia_changed_event_listener__on_multimedia_changed.html',1,'DOX_IADLXMultimediaChangedEventListener']]],
  ['onpowertuningchanged_14',['OnPowerTuningChanged',['../_d_o_x__i_a_d_l_x_power_tuning_changed_listener__on_power_tuning_changed.html',1,'DOX_IADLXPowerTuningChangedListener']]],
  ['operating_20systems_15',['Supported Operating Systems',['../page_guide_os.html',1,'page_guide_spe']]],
  ['orientation_16',['Orientation',['../_d_o_x__i_a_d_l_x_desktop__orientation.html',1,'DOX_IADLXDesktop']]],
  ['orientation_5flandscape_17',['ORIENTATION_LANDSCAPE',['../_a_d_l_x_defines_8h.html#gadf0d7e5ecd72b38ab053c0b9065edd53a3bf4f4e993f58d42ec617c8159b56e00',1,'adlx']]],
  ['orientation_5flandscape_5fflipped_18',['ORIENTATION_LANDSCAPE_FLIPPED',['../_a_d_l_x_defines_8h.html#gadf0d7e5ecd72b38ab053c0b9065edd53a84c63d50b59a564bd4093123437a7526',1,'adlx']]],
  ['orientation_5fportrait_19',['ORIENTATION_PORTRAIT',['../_a_d_l_x_defines_8h.html#gadf0d7e5ecd72b38ab053c0b9065edd53aea15f906381aca4c2cce57b40ca75882',1,'adlx']]],
  ['orientation_5fportrait_5fflipped_20',['ORIENTATION_PORTRAIT_FLIPPED',['../_a_d_l_x_defines_8h.html#gadf0d7e5ecd72b38ab053c0b9065edd53ae72b80c51de49f8eaea72d0d589d7d89',1,'adlx']]],
  ['other_21',['OTHER',['../_a_d_l_x_defines_8h.html#ga0523abdbbb46c6b9bc85475b6ed4f2e6a63697d900131957a8e23716781afd983',1,'adlx']]]
];
