var searchData=
[
  ['samples_0',['Samples',['../domain_sample_page.html',1,'ADLX Samples'],['../page_sample_c.html',1,'C Samples'],['../page_sample_cs.html',1,'C# Samples'],['../page_sample_cpp.html',1,'C++ Samples'],['../page_sample_java.html',1,'Java Samples'],['../page_sample_py.html',1,'Python Samples']]],
  ['scantype_1',['ScanType',['../_d_o_x__i_a_d_l_x_display__scan_type.html',1,'DOX_IADLXDisplay']]],
  ['sdk_20references_2',['ADLX SDK References',['../page_sdk.html',1,'']]],
  ['service_20application_3',['Using ADLX in a Windows system service application',['../page_guide_usingservice.html',1,'page_guide_advanced']]],
  ['servicecall_4',['ServiceCall',['../domain_cpp_sample_servicecall.html',1,'ServiceCall'],['../domain_c_sample_servicecall.html',1,'ServiceCall']]],
  ['setalluser3dlut_5',['SetAllUser3DLUT',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t__set_all_user3_d_l_u_t.html',1,'DOX_IADLXDisplay3DLUT']]],
  ['setbacklightadaptiveenabled_6',['SetBacklightAdaptiveEnabled',['../_d_o_x__i_a_d_l_x_display_vari_bright1__set_backlight_adaptive_enabled.html',1,'DOX_IADLXDisplayVariBright1']]],
  ['setbalanced_7',['SetBalanced',['../_d_o_x__i_a_d_l_x_display_vari_bright__set_balanced.html',1,'SetBalanced'],['../_d_o_x__i_a_d_l_x_g_p_u_preset_tuning__set_balanced.html',1,'SetBalanced']]],
  ['setbatterylifeenabled_8',['SetBatteryLifeEnabled',['../_d_o_x__i_a_d_l_x_display_vari_bright1__set_battery_life_enabled.html',1,'DOX_IADLXDisplayVariBright1']]],
  ['setbias_9',['SetBias',['../_d_o_x__i_a_d_l_x_smart_shift_max__set_bias.html',1,'DOX_IADLXSmartShiftMax']]],
  ['setbiasmode_10',['SetBiasMode',['../_d_o_x__i_a_d_l_x_smart_shift_max__set_bias_mode.html',1,'DOX_IADLXSmartShiftMax']]],
  ['setblanked_11',['SetBlanked',['../_d_o_x__i_a_d_l_x_display_blanking__set_blanked.html',1,'DOX_IADLXDisplayBlanking']]],
  ['setbrightness_12',['SetBrightness',['../_d_o_x__i_a_d_l_x_display_custom_color__set_brightness.html',1,'DOX_IADLXDisplayCustomColor']]],
  ['setcontrast_13',['SetContrast',['../_d_o_x__i_a_d_l_x_display_custom_color__set_contrast.html',1,'DOX_IADLXDisplayCustomColor']]],
  ['setdegammaramp_14',['SetDeGammaRamp',['../_d_o_x__i_a_d_l_x_display_gamma__set_de_gamma_ramp_file.html',1,'SetDeGammaRamp'],['../_d_o_x__i_a_d_l_x_display_gamma__set_de_gamma_ramp_memory.html',1,'SetDeGammaRamp']]],
  ['setenabled_15',['SetEnabled',['../_d_o_x__i_a_d_l_x3_d_anti_lag__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_chill__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_boost__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_image_sharpening__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_enhanced_sync__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_frame_rate_target_control__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_morphological_anti_aliasing__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_anisotropic_filtering__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_radeon_super_resolution__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_a_m_d_fluid_motion_frames__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x3_d_image_sharpen_desktop__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_free_sync__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_v_s_r__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_g_p_u_scaling__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_integer_scaling__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_h_d_c_p__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_vari_bright__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_dynamic_refresh_rate_control__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_display_free_sync_color_accuracy__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_video_upscale__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_smart_shift_eco__set_enabled.html',1,'SetEnabled'],['../_d_o_x__i_a_d_l_x_smart_access_memory__set_enabled.html',1,'SetEnabled']]],
  ['setenabledhdmiqualitydetection_16',['SetEnabledHDMIQualityDetection',['../_d_o_x__i_a_d_l_x_display_connectivity_experience__set_enabled_h_d_m_i_quality_detection.html',1,'DOX_IADLXDisplayConnectivityExperience']]],
  ['setfanspeed_17',['SetFanSpeed',['../_d_o_x__i_a_d_l_x_manual_fan_tuning_state__set_fan_speed.html',1,'DOX_IADLXManualFanTuningState']]],
  ['setfantuningstates_18',['SetFanTuningStates',['../_d_o_x__i_a_d_l_x_manual_fan_tuning__set_fan_tuning_states.html',1,'DOX_IADLXManualFanTuning']]],
  ['setfps_19',['SetFPS',['../_d_o_x__i_a_d_l_x3_d_frame_rate_target_control__set_f_p_s.html',1,'DOX_IADLX3DFrameRateTargetControl']]],
  ['setfrequency_20',['SetFrequency',['../_d_o_x__i_a_d_l_x_manual_tuning_state__set_frequency.html',1,'DOX_IADLXManualTuningState']]],
  ['setfullscreenvideoenabled_21',['SetFullScreenVideoEnabled',['../_d_o_x__i_a_d_l_x_display_vari_bright1__set_full_screen_video_enabled.html',1,'DOX_IADLXDisplayVariBright1']]],
  ['setgamut_22',['SetGamut',['../_d_o_x__i_a_d_l_x_display_gamut__set_gamut__p_w__p_g.html',1,'SetGamut'],['../_d_o_x__i_a_d_l_x_display_gamut__set_gamut__c_w__p_g.html',1,'SetGamut'],['../_d_o_x__i_a_d_l_x_display_gamut__set_gamut__p_w__c_g.html',1,'SetGamut'],['../_d_o_x__i_a_d_l_x_display_gamut__set_gamut__c_w__c_g.html',1,'SetGamut']]],
  ['setgpumaxfrequency_23',['SetGPUMaxFrequency',['../_d_o_x__i_a_d_l_x_manual_graphics_tuning2__set_g_p_u_max_frequency.html',1,'DOX_IADLXManualGraphicsTuning2']]],
  ['setgpuminfrequency_24',['SetGPUMinFrequency',['../_d_o_x__i_a_d_l_x_manual_graphics_tuning2__set_g_p_u_min_frequency.html',1,'DOX_IADLXManualGraphicsTuning2']]],
  ['setgputuningstates_25',['SetGPUTuningStates',['../_d_o_x__i_a_d_l_x_manual_graphics_tuning1__set_g_p_u_tuning_states.html',1,'DOX_IADLXManualGraphicsTuning1']]],
  ['setgpuvoltage_26',['SetGPUVoltage',['../_d_o_x__i_a_d_l_x_manual_graphics_tuning2__set_g_p_u_voltage.html',1,'DOX_IADLXManualGraphicsTuning2']]],
  ['sethdruser3dlut_27',['SetHDRUser3DLUT',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t__set_h_d_r_user3_d_l_u_t.html',1,'DOX_IADLXDisplay3DLUT']]],
  ['sethue_28',['SetHue',['../_d_o_x__i_a_d_l_x_display_custom_color__set_hue.html',1,'DOX_IADLXDisplayCustomColor']]],
  ['setlevel_29',['SetLevel',['../_d_o_x__i_a_d_l_x3_d_anti_lag1__set_level.html',1,'SetLevel'],['../_d_o_x__i_a_d_l_x3_d_anti_aliasing__set_level.html',1,'SetLevel'],['../_d_o_x__i_a_d_l_x3_d_anisotropic_filtering__set_level.html',1,'SetLevel'],['../_d_o_x__i_a_d_l_x3_d_tessellation__set_level.html',1,'SetLevel']]],
  ['setmaxfps_30',['SetMaxFPS',['../_d_o_x__i_a_d_l_x3_d_chill__set_max_f_p_s.html',1,'DOX_IADLX3DChill']]],
  ['setmaximizebattery_31',['SetMaximizeBattery',['../_d_o_x__i_a_d_l_x_display_vari_bright__set_maximize_battery.html',1,'DOX_IADLXDisplayVariBright']]],
  ['setmaximizebrightness_32',['SetMaximizeBrightness',['../_d_o_x__i_a_d_l_x_display_vari_bright__set_maximize_brightness.html',1,'DOX_IADLXDisplayVariBright']]],
  ['setmaxperformancemetricshistorysize_33',['SetMaxPerformanceMetricsHistorySize',['../_d_o_x__i_a_d_l_x_performance_monitoring_services__set_max_performance_metrics_history_size.html',1,'DOX_IADLXPerformanceMonitoringServices']]],
  ['setmaxvramfrequency_34',['SetMaxVRAMFrequency',['../_d_o_x__i_a_d_l_x_manual_v_r_a_m_tuning2__set_max_v_r_a_m_frequency.html',1,'DOX_IADLXManualVRAMTuning2']]],
  ['setmemorytimingdescription_35',['SetMemoryTimingDescription',['../_d_o_x__i_a_d_l_x_manual_v_r_a_m_tuning1__set_memory_timing_description.html',1,'SetMemoryTimingDescription'],['../_d_o_x__i_a_d_l_x_manual_v_r_a_m_tuning2__set_memory_timing_description.html',1,'SetMemoryTimingDescription']]],
  ['setmethod_36',['SetMethod',['../_d_o_x__i_a_d_l_x3_d_anti_aliasing__set_method.html',1,'DOX_IADLX3DAntiAliasing']]],
  ['setminacousticlimit_37',['SetMinAcousticLimit',['../_d_o_x__i_a_d_l_x_manual_fan_tuning__set_min_acoustic_limit.html',1,'DOX_IADLXManualFanTuning']]],
  ['setminfanspeed_38',['SetMinFanSpeed',['../_d_o_x__i_a_d_l_x_manual_fan_tuning__set_min_fan_speed.html',1,'DOX_IADLXManualFanTuning']]],
  ['setminfps_39',['SetMinFPS',['../_d_o_x__i_a_d_l_x3_d_chill__set_min_f_p_s.html',1,'DOX_IADLX3DChill']]],
  ['setmode_40',['SetMode',['../_d_o_x__i_a_d_l_x3_d_wait_for_vertical_refresh__set_mode.html',1,'SetMode'],['../_d_o_x__i_a_d_l_x3_d_anti_aliasing__set_mode.html',1,'SetMode'],['../_d_o_x__i_a_d_l_x3_d_tessellation__set_mode.html',1,'SetMode'],['../_d_o_x__i_a_d_l_x_display_scaling_mode__set_mode.html',1,'SetMode']]],
  ['setoptimizebattery_41',['SetOptimizeBattery',['../_d_o_x__i_a_d_l_x_display_vari_bright__set_optimize_battery.html',1,'DOX_IADLXDisplayVariBright']]],
  ['setoptimizebrightness_42',['SetOptimizeBrightness',['../_d_o_x__i_a_d_l_x_display_vari_bright__set_optimize_brightness.html',1,'DOX_IADLXDisplayVariBright']]],
  ['setpowerlimit_43',['SetPowerLimit',['../_d_o_x__i_a_d_l_x_manual_power_tuning__set_power_limit.html',1,'DOX_IADLXManualPowerTuning']]],
  ['setpowersaver_44',['SetPowerSaver',['../_d_o_x__i_a_d_l_x_g_p_u_preset_tuning__set_power_saver.html',1,'DOX_IADLXGPUPresetTuning']]],
  ['setquiet_45',['SetQuiet',['../_d_o_x__i_a_d_l_x_g_p_u_preset_tuning__set_quiet.html',1,'DOX_IADLXGPUPresetTuning']]],
  ['setrage_46',['SetRage',['../_d_o_x__i_a_d_l_x_g_p_u_preset_tuning__set_rage.html',1,'DOX_IADLXGPUPresetTuning']]],
  ['setregamma36_47',['SetReGamma36',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma36.html',1,'DOX_IADLXDisplayGamma']]],
  ['setregammabt709_48',['SetReGammaBT709',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_b_t709.html',1,'DOX_IADLXDisplayGamma']]],
  ['setregammacoefficient_49',['SetReGammaCoefficient',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_coefficient.html',1,'DOX_IADLXDisplayGamma']]],
  ['setregammapq_50',['SetReGammaPQ',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_p_q.html',1,'DOX_IADLXDisplayGamma']]],
  ['setregammapq2084interim_51',['SetReGammaPQ2084Interim',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_p_q2084_interim.html',1,'DOX_IADLXDisplayGamma']]],
  ['setregammaramp_52',['SetReGammaRamp',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_ramp_file.html',1,'SetReGammaRamp'],['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_ramp_memory.html',1,'SetReGammaRamp']]],
  ['setregammasrgb_53',['SetReGammaSRGB',['../_d_o_x__i_a_d_l_x_display_gamma__set_re_gamma_s_r_g_b.html',1,'DOX_IADLXDisplayGamma']]],
  ['setrelativepreemphasis_54',['SetRelativePreEmphasis',['../_d_o_x__i_a_d_l_x_display_connectivity_experience__set_relative_pre_emphasis.html',1,'DOX_IADLXDisplayConnectivityExperience']]],
  ['setrelativevoltageswing_55',['SetRelativeVoltageSwing',['../_d_o_x__i_a_d_l_x_display_connectivity_experience__set_relative_voltage_swing.html',1,'DOX_IADLXDisplayConnectivityExperience']]],
  ['setresolution_56',['SetResolution',['../_d_o_x__i_a_d_l_x3_d_boost__set_resolution.html',1,'DOX_IADLX3DBoost']]],
  ['setsamplinginterval_57',['SetSamplingInterval',['../_d_o_x__i_a_d_l_x_performance_monitoring_services__set_sampling_interval.html',1,'DOX_IADLXPerformanceMonitoringServices']]],
  ['setsaturation_58',['SetSaturation',['../_d_o_x__i_a_d_l_x_display_custom_color__set_saturation.html',1,'DOX_IADLXDisplayCustomColor']]],
  ['setscedisabled_59',['SetSCEDisabled',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t__set_s_c_e_disabled.html',1,'DOX_IADLXDisplay3DLUT']]],
  ['setscedynamiccontrast_60',['SetSCEDynamicContrast',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t__set_s_c_e_dynamic_contrast.html',1,'DOX_IADLXDisplay3DLUT']]],
  ['setscevividgaming_61',['SetSCEVividGaming',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t__set_s_c_e_vivid_gaming.html',1,'DOX_IADLXDisplay3DLUT']]],
  ['setsdruser3dlut_62',['SetSDRUser3DLUT',['../_d_o_x__i_a_d_l_x_display3_d_l_u_t__set_s_d_r_user3_d_l_u_t.html',1,'DOX_IADLXDisplay3DLUT']]],
  ['setsharpness_63',['SetSharpness',['../_d_o_x__i_a_d_l_x3_d_image_sharpening__set_sharpness.html',1,'SetSharpness'],['../_d_o_x__i_a_d_l_x3_d_radeon_super_resolution__set_sharpness.html',1,'SetSharpness'],['../_d_o_x__i_a_d_l_x_video_upscale__set_sharpness.html',1,'SetSharpness']]],
  ['settargetfanspeed_64',['SetTargetFanSpeed',['../_d_o_x__i_a_d_l_x_manual_fan_tuning__set_target_fan_speed.html',1,'DOX_IADLXManualFanTuning']]],
  ['settdclimit_65',['SetTDCLimit',['../_d_o_x__i_a_d_l_x_manual_power_tuning__set_t_d_c_limit.html',1,'DOX_IADLXManualPowerTuning']]],
  ['settemperature_66',['SetTemperature',['../_d_o_x__i_a_d_l_x_display_custom_color__set_temperature.html',1,'SetTemperature'],['../_d_o_x__i_a_d_l_x_manual_fan_tuning_state__set_temperature.html',1,'SetTemperature']]],
  ['setturbo_67',['SetTurbo',['../_d_o_x__i_a_d_l_x_g_p_u_preset_tuning__set_turbo.html',1,'DOX_IADLXGPUPresetTuning']]],
  ['setunblanked_68',['SetUnblanked',['../_d_o_x__i_a_d_l_x_display_blanking__set_unblanked.html',1,'DOX_IADLXDisplayBlanking']]],
  ['setvalue_69',['SetValue',['../_d_o_x__i_a_d_l_x_display_color_depth__set_value.html',1,'SetValue'],['../_d_o_x__i_a_d_l_x_display_pixel_format__set_value.html',1,'SetValue'],['../_d_o_x__i_a_d_l_x_display_resolution__set_value.html',1,'SetValue']]],
  ['setvoltage_70',['SetVoltage',['../_d_o_x__i_a_d_l_x_manual_tuning_state__set_voltage.html',1,'DOX_IADLXManualTuningState']]],
  ['setvramtuningstates_71',['SetVRAMTuningStates',['../_d_o_x__i_a_d_l_x_manual_v_r_a_m_tuning1__set_v_r_a_m_tuning_states.html',1,'DOX_IADLXManualVRAMTuning1']]],
  ['setwindowspowermodeenabled_72',['SetWindowsPowerModeEnabled',['../_d_o_x__i_a_d_l_x_display_vari_bright1__set_windows_power_mode_enabled.html',1,'DOX_IADLXDisplayVariBright1']]],
  ['setzerorpmstate_73',['SetZeroRPMState',['../_d_o_x__i_a_d_l_x_manual_fan_tuning__set_zero_r_p_m_state.html',1,'DOX_IADLXManualFanTuning']]],
  ['sharememory_74',['ShareMemory',['../cpp_sample__share_memory.html',1,'ShareMemory'],['../c_sample__share_memory.html',1,'ShareMemory']]],
  ['size_75',['Size',['../_d_o_x__i_a_d_l_x_list__size.html',1,'Size'],['../_d_o_x__i_a_d_l_x_desktop__size.html',1,'Size']]],
  ['smartaccessmemory_76',['SmartAccessMemory',['../cpp_sam.html',1,'SmartAccessMemory'],['../c_sam.html',1,'SmartAccessMemory']]],
  ['smartshift_77',['SmartShift',['../_d_o_x__i_a_d_l_x_system_metrics__smart_shift.html',1,'DOX_IADLXSystemMetrics']]],
  ['smartshifteco_78',['SmartShiftEco',['../cpp_sseco.html',1,'SmartShiftEco'],['../c_sseco.html',1,'SmartShiftEco']]],
  ['smartshiftmax_79',['SmartShiftMax',['../cpp_ssm.html',1,'SmartShiftMax'],['../c_ssm.html',1,'SmartShiftMax']]],
  ['specifications_80',['Specifications',['../page_guide_spe.html',1,'page_adlxprogrammingguide']]],
  ['ssm_5fbias_5fauto_81',['SSM_BIAS_AUTO',['../_a_d_l_x_defines_8h.html#gae2895828b9a8b0345e1fb8bf416ff1b4aa01f2492c707f2d545a726a70bfe4885',1,'ADLXDefines.h']]],
  ['ssm_5fbias_5fmanual_82',['SSM_BIAS_MANUAL',['../_a_d_l_x_defines_8h.html#gae2895828b9a8b0345e1fb8bf416ff1b4af35e1bfcb1955e0e0c900876c1c67746',1,'ADLXDefines.h']]],
  ['start_83',['Quick Start',['../page_guide_qs.html',1,'page_adlxprogrammingguide']]],
  ['startoverclockgpu_84',['StartOverclockGPU',['../_d_o_x__i_a_d_l_x_g_p_u_auto_tuning__start_overclock_g_p_u.html',1,'DOX_IADLXGPUAutoTuning']]],
  ['startoverclockvram_85',['StartOverclockVRAM',['../_d_o_x__i_a_d_l_x_g_p_u_auto_tuning__start_overclock_v_r_a_m.html',1,'DOX_IADLXGPUAutoTuning']]],
  ['startperformancemetricstracking_86',['StartPerformanceMetricsTracking',['../_d_o_x__i_a_d_l_x_performance_monitoring_services__start_performance_metrics_tracking.html',1,'DOX_IADLXPerformanceMonitoringServices']]],
  ['startpoweroff_87',['StartPowerOff',['../_d_o_x__i_a_d_l_x_g_p_u2__start_power_off.html',1,'DOX_IADLXGPU2']]],
  ['startundervoltgpu_88',['StartUndervoltGPU',['../_d_o_x__i_a_d_l_x_g_p_u_auto_tuning__start_undervolt_g_p_u.html',1,'DOX_IADLXGPUAutoTuning']]],
  ['step_89',['step',['../group__structures_val.html#ae0e545b501a683c565f08089ed3e8023',1,'ADLX_IntRange']]],
  ['stopperformancemetricstracking_90',['StopPerformanceMetricsTracking',['../_d_o_x__i_a_d_l_x_performance_monitoring_services__stop_performance_metrics_tracking.html',1,'DOX_IADLXPerformanceMonitoringServices']]],
  ['structs_91',['ADLX Structs',['../group__structures_val.html',1,'']]],
  ['subscribing_20to_20event_20notifications_20using_20adlx_92',['Subscribing to Event Notifications using ADLX',['../page_guide_event.html',1,'page_guide_qs']]],
  ['subsystemid_93',['SubSystemId',['../_d_o_x__i_a_d_l_x_g_p_u__sub_system_id.html',1,'DOX_IADLXGPU']]],
  ['subsystemvendorid_94',['SubSystemVendorId',['../_d_o_x__i_a_d_l_x_g_p_u__sub_system_vendor_id.html',1,'DOX_IADLXGPU']]],
  ['supported_20operating_20systems_95',['Supported Operating Systems',['../page_guide_os.html',1,'page_guide_spe']]],
  ['supported_20programming_20languages_96',['Supported Programming Languages',['../page_guide_languages.html',1,'page_guide_spe']]],
  ['sync3dreceive_97',['Sync3DReceive',['../cpp__sync3_d_receive.html',1,'Sync3DReceive'],['../c__sync3_d_receive.html',1,'Sync3DReceive']]],
  ['sync_5forigin_5fexternal_98',['SYNC_ORIGIN_EXTERNAL',['../_a_d_l_x_defines_8h.html#ga7a1e20106faef482c0664c546e04ba00a8f0083602d13ae71103b333d6c9c9d00',1,'ADLXDefines.h']]],
  ['sync_5forigin_5finternal_99',['SYNC_ORIGIN_INTERNAL',['../_a_d_l_x_defines_8h.html#ga7a1e20106faef482c0664c546e04ba00a9675678b0b44b0e114901d2e49441eeb',1,'ADLXDefines.h']]],
  ['sync_5forigin_5funknown_100',['SYNC_ORIGIN_UNKNOWN',['../_a_d_l_x_defines_8h.html#ga7a1e20106faef482c0664c546e04ba00a4ba8600162d2d062803b6ff6bc43d8e9',1,'ADLXDefines.h']]],
  ['syncdisplayreceive_101',['SyncDisplayReceive',['../cpp__sync_display_receive.html',1,'SyncDisplayReceive'],['../c__sync_display_receive.html',1,'SyncDisplayReceive']]],
  ['syncgputuning_102',['SyncGPUTuning',['../cpp__sync_g_p_u_tuning.html',1,'SyncGPUTuning'],['../c__sync_g_p_u_tuning.html',1,'SyncGPUTuning']]],
  ['syncmultimedia_103',['SyncMultimedia',['../cpp__sync_multimedia.html',1,'SyncMultimedia'],['../c__sync_multimedia.html',1,'SyncMultimedia']]],
  ['syncpowertuning_104',['SyncPowerTuning',['../cpp__sync_power_tuning.html',1,'SyncPowerTuning'],['../c__sync_power_tuning.html',1,'SyncPowerTuning']]],
  ['system_105',['System',['../system.html',1,'page_interfaces']]],
  ['system_20service_20application_106',['Using ADLX in a Windows system service application',['../page_guide_usingservice.html',1,'page_guide_advanced']]],
  ['systemram_107',['SystemRAM',['../_d_o_x__i_a_d_l_x_system_metrics__system_r_a_m.html',1,'DOX_IADLXSystemMetrics']]],
  ['systems_108',['Supported Operating Systems',['../page_guide_os.html',1,'page_guide_spe']]]
];
