var searchData=
[
  ['deleteresolution_1314',['DeleteResolution',['../_d_o_x__i_a_d_l_x_display_custom_resolution__delete_resolution.html',1,'DOX_IADLXDisplayCustomResolution']]],
  ['desktop_1315',['Desktop',['../c_sample__desktop.html',1,'c_samples_more'],['../cpp_sample__desktop.html',1,'cpp_samples_more'],['../desktop.html',1,'page_interfaces']]],
  ['desktop_20files_1316',['Desktop Files',['../c_samples_files_desktop.html',1,'c_samples_filedesc'],['../cpp_samples_files_desktop.html',1,'cpp_samples_filedesc']]],
  ['desktopsevent_1317',['DesktopsEvent',['../c_sample_desktopevent.html',1,'c_sample_globalsync'],['../cpp_sample_desktopevent.html',1,'cpp_sample_globalsync']]],
  ['destroy_1318',['Destroy',['../_d_o_x__i_a_d_l_x_simple_eyefinity__destroy.html',1,'DOX_IADLXSimpleEyefinity']]],
  ['destroyall_1319',['DestroyAll',['../_d_o_x__i_a_d_l_x_simple_eyefinity__destroy_all.html',1,'DOX_IADLXSimpleEyefinity']]],
  ['deviceid_1320',['DeviceId',['../_d_o_x__i_a_d_l_x_g_p_u__device_id.html',1,'DOX_IADLXGPU']]],
  ['disclaimer_1321',['Disclaimer',['../page_legal__disclaimer.html',1,'page_legal_notices']]],
  ['display_1322',['Display',['../c_sample__display.html',1,'c_samples_more'],['../cpp_sample__display.html',1,'cpp_samples_more'],['../display.html',1,'page_interfaces']]],
  ['display_20files_1323',['Display Files',['../c_samples_files_display.html',1,'c_samples_filedesc'],['../cpp_samples_files_display.html',1,'cpp_samples_filedesc']]],
  ['display3dlut_1324',['Display3DLUT',['../c_sample_display3_d_l_u_t.html',1,'c_sample_Display'],['../cpp_sample_display3_d_l_u_t.html',1,'cpp_sample_Display']]],
  ['displaycolordepth_1325',['DisplayColorDepth',['../c_display__color_depth.html',1,'c_sample_Display'],['../cpp_display__color_depth.html',1,'cpp_sample_Display']]],
  ['displaycustomcolor_1326',['DisplayCustomColor',['../c_display__custom_color.html',1,'c_sample_Display'],['../cpp_display__custom_color.html',1,'cpp_sample_Display']]],
  ['displaycustomresolution_1327',['DisplayCustomResolution',['../c_display__custom_resolution.html',1,'c_sample_Display'],['../cpp_display__custom_resolution.html',1,'cpp_sample_Display']]],
  ['displayevents_1328',['DisplayEvents',['../c_sample_display_events.html',1,'c_sample_Display'],['../cpp_sample_display_events.html',1,'cpp_sample_Display'],['../cs_sample_display_events.html',1,'cs_samples_more'],['../java_sample_display_events.html',1,'java_samples_more'],['../py_sample_display_events.html',1,'py_samples_more']]],
  ['displayfreesync_1329',['DisplayFreeSync',['../c_display__free_sync.html',1,'c_sample_Display'],['../cpp_display__free_sync.html',1,'cpp_sample_Display']]],
  ['displaygamma_1330',['DisplayGamma',['../c_sample_display_gamma.html',1,'c_sample_Display'],['../cpp_sample_display_gamma.html',1,'cpp_sample_Display']]],
  ['displaygamut_1331',['DisplayGamut',['../c_sample_display_gamut.html',1,'c_sample_Display'],['../cpp_sample_display_gamut.html',1,'cpp_sample_Display']]],
  ['displaygpuscaling_1332',['DisplayGPUScaling',['../c_display__g_p_u_scaling.html',1,'c_sample_Display'],['../cpp_display__g_p_u_scaling.html',1,'cpp_sample_Display']]],
  ['displayhdcp_1333',['DisplayHDCP',['../c_display__h_d_c_p.html',1,'c_sample_Display'],['../cpp_display__h_d_c_p.html',1,'cpp_sample_Display']]],
  ['displayinfo_1334',['DisplayInfo',['../c_sample_displayinfo.html',1,'c_sample_Display'],['../cpp_sample_displayinfo.html',1,'cpp_sample_Display'],['../cs_sample_displayinfo.html',1,'cs_samples_more'],['../java_sample_displayinfo.html',1,'java_samples_more'],['../py_sample_displayinfo.html',1,'py_samples_more']]],
  ['displayintegerscaling_1335',['DisplayIntegerScaling',['../c_display__integer_scaling.html',1,'c_sample_Display'],['../cpp_display__integer_scaling.html',1,'cpp_sample_Display']]],
  ['displayorientation_1336',['DisplayOrientation',['../_d_o_x__i_a_d_l_x_eyefinity_desktop__display_orientation.html',1,'DOX_IADLXEyefinityDesktop']]],
  ['displaypixelformat_1337',['DisplayPixelFormat',['../c_display__pixel_format.html',1,'c_sample_Display'],['../cpp_display__pixel_format.html',1,'cpp_sample_Display']]],
  ['displayscalingmode_1338',['DisplayScalingMode',['../c_display__scaling_mode.html',1,'c_sample_Display'],['../cpp_display__scaling_mode.html',1,'cpp_sample_Display']]],
  ['displaysettingsevent_1339',['DisplaySettingsEvent',['../c_display_settings_event.html',1,'c_sample_Display'],['../cpp_display_settings_event.html',1,'cpp_sample_Display']]],
  ['displaysize_1340',['DisplaySize',['../_d_o_x__i_a_d_l_x_eyefinity_desktop__display_size.html',1,'DOX_IADLXEyefinityDesktop']]],
  ['displaytopleft_1341',['DisplayTopLeft',['../_d_o_x__i_a_d_l_x_eyefinity_desktop__display_top_left.html',1,'DOX_IADLXEyefinityDesktop']]],
  ['displaytype_1342',['DisplayType',['../_d_o_x__i_a_d_l_x_display__display_type.html',1,'DOX_IADLXDisplay']]],
  ['displayvaribright_1343',['DisplayVariBright',['../c_display__display_vari_bright.html',1,'c_sample_Display'],['../cpp_display__display_vari_bright.html',1,'cpp_sample_Display']]],
  ['displayvsr_1344',['DisplayVSR',['../c_display__v_s_r.html',1,'c_sample_Display'],['../cpp_display__v_s_r.html',1,'cpp_sample_Display']]],
  ['driverpath_1345',['DriverPath',['../_d_o_x__i_a_d_l_x_g_p_u__driver_path.html',1,'DOX_IADLXGPU']]]
];
