var searchData=
[
  ['deleteresolution_0',['DeleteResolution',['../_d_o_x__i_a_d_l_x_display_custom_resolution__delete_resolution.html',1,'DOX_IADLXDisplayCustomResolution']]],
  ['desktop_1',['Desktop',['../desktop.html',1,'Desktop'],['../domain_c_sample__desktop.html',1,'Desktop'],['../domain_cpp_sample__desktop.html',1,'Desktop']]],
  ['desktopsevent_2',['DesktopsEvent',['../cpp_sample_desktopevent.html',1,'DesktopsEvent'],['../c_sample_desktopevent.html',1,'DesktopsEvent']]],
  ['destroy_3',['Destroy',['../_d_o_x__i_a_d_l_x_simple_eyefinity__destroy.html',1,'DOX_IADLXSimpleEyefinity']]],
  ['destroyall_4',['DestroyAll',['../_d_o_x__i_a_d_l_x_simple_eyefinity__destroy_all.html',1,'DOX_IADLXSimpleEyefinity']]],
  ['device_20library_20extra_5',['AMD Device Library eXtra',['../index.html',1,'']]],
  ['deviceid_6',['DeviceId',['../_d_o_x__i_a_d_l_x_g_p_u__device_id.html',1,'DOX_IADLXGPU']]],
  ['disclaimers_7',['Disclaimers',['../page_legal__disclaimer.html',1,'Disclaimers'],['../page_legal.html',1,'Legal Information and Compliance/Disclaimers']]],
  ['display_8',['Display',['../display.html',1,'Display'],['../domain_c_sample__display.html',1,'Display'],['../domain_cpp_sample__display.html',1,'Display']]],
  ['display3dlut_9',['Display3DLUT',['../cpp_sample_display3_d_l_u_t.html',1,'Display3DLUT'],['../c_sample_display3_d_l_u_t.html',1,'Display3DLUT']]],
  ['displayblanking_10',['DisplayBlanking',['../cpp_sample_display_blanking.html',1,'DisplayBlanking'],['../c_sample_display_blanking.html',1,'DisplayBlanking']]],
  ['displaycolordepth_11',['DisplayColorDepth',['../cpp_display__color_depth.html',1,'DisplayColorDepth'],['../c_display__color_depth.html',1,'DisplayColorDepth']]],
  ['displayconnectivityexperience_12',['DisplayConnectivityExperience',['../cpp_display__display_connectivity_experience.html',1,'DisplayConnectivityExperience'],['../c_display__display_connectivity_experience.html',1,'DisplayConnectivityExperience']]],
  ['displaycustomcolor_13',['DisplayCustomColor',['../cpp_display__custom_color.html',1,'DisplayCustomColor'],['../c_display__custom_color.html',1,'DisplayCustomColor']]],
  ['displaycustomresolution_14',['DisplayCustomResolution',['../cpp_display__custom_resolution.html',1,'DisplayCustomResolution'],['../c_display__custom_resolution.html',1,'DisplayCustomResolution']]],
  ['displaydynamicrefreshratecontrol_15',['DisplayDynamicRefreshRateControl',['../cpp_display__dynamic_refresh_rate_control.html',1,'DisplayDynamicRefreshRateControl'],['../c_display__dynamic_refresh_rate_control.html',1,'DisplayDynamicRefreshRateControl']]],
  ['displayevents_16',['DisplayEvents',['../cpp_sample_display_events.html',1,'DisplayEvents'],['../c_sample_display_events.html',1,'DisplayEvents'],['../cs_sample_display_events.html',1,'DisplayEvents'],['../java_sample_display_events.html',1,'DisplayEvents'],['../py_sample_display_events.html',1,'DisplayEvents']]],
  ['displayfreesync_17',['DisplayFreeSync',['../cpp_display__free_sync.html',1,'DisplayFreeSync'],['../c_display__free_sync.html',1,'DisplayFreeSync']]],
  ['displayfreesynccoloraccuracy_18',['DisplayFreeSyncColorAccuracy',['../cpp_display__free_sync_color_accuracy.html',1,'DisplayFreeSyncColorAccuracy'],['../c_display__free_sync_color_accuracy.html',1,'DisplayFreeSyncColorAccuracy']]],
  ['displaygamma_19',['DisplayGamma',['../cpp_sample_display_gamma.html',1,'DisplayGamma'],['../c_sample_display_gamma.html',1,'DisplayGamma']]],
  ['displaygamut_20',['DisplayGamut',['../cpp_sample_display_gamut.html',1,'DisplayGamut'],['../c_sample_display_gamut.html',1,'DisplayGamut']]],
  ['displaygpuscaling_21',['DisplayGPUScaling',['../cpp_display__g_p_u_scaling.html',1,'DisplayGPUScaling'],['../c_display__g_p_u_scaling.html',1,'DisplayGPUScaling']]],
  ['displayhdcp_22',['DisplayHDCP',['../cpp_display__h_d_c_p.html',1,'DisplayHDCP'],['../c_display__h_d_c_p.html',1,'DisplayHDCP']]],
  ['displayinfo_23',['DisplayInfo',['../cpp_sample_displayinfo.html',1,'DisplayInfo'],['../c_sample_displayinfo.html',1,'DisplayInfo'],['../cs_sample_displayinfo.html',1,'DisplayInfo'],['../java_sample_displayinfo.html',1,'DisplayInfo'],['../py_sample_displayinfo.html',1,'DisplayInfo']]],
  ['displayintegerscaling_24',['DisplayIntegerScaling',['../cpp_display__integer_scaling.html',1,'DisplayIntegerScaling'],['../c_display__integer_scaling.html',1,'DisplayIntegerScaling']]],
  ['displayorientation_25',['DisplayOrientation',['../_d_o_x__i_a_d_l_x_eyefinity_desktop__display_orientation.html',1,'DOX_IADLXEyefinityDesktop']]],
  ['displaypixelformat_26',['DisplayPixelFormat',['../cpp_display__pixel_format.html',1,'DisplayPixelFormat'],['../c_display__pixel_format.html',1,'DisplayPixelFormat']]],
  ['displayscalingmode_27',['DisplayScalingMode',['../cpp_display__scaling_mode.html',1,'DisplayScalingMode'],['../c_display__scaling_mode.html',1,'DisplayScalingMode']]],
  ['displaysize_28',['DisplaySize',['../_d_o_x__i_a_d_l_x_eyefinity_desktop__display_size.html',1,'DOX_IADLXEyefinityDesktop']]],
  ['displaytopleft_29',['DisplayTopLeft',['../_d_o_x__i_a_d_l_x_eyefinity_desktop__display_top_left.html',1,'DOX_IADLXEyefinityDesktop']]],
  ['displaytype_30',['DisplayType',['../_d_o_x__i_a_d_l_x_display__display_type.html',1,'DOX_IADLXDisplay']]],
  ['displayvaribright_31',['DisplayVariBright',['../cpp_display__display_vari_bright.html',1,'DisplayVariBright'],['../c_display__display_vari_bright.html',1,'DisplayVariBright']]],
  ['displayvsr_32',['DisplayVSR',['../cpp_display__v_s_r.html',1,'DisplayVSR'],['../c_display__v_s_r.html',1,'DisplayVSR']]],
  ['driverpath_33',['DriverPath',['../_d_o_x__i_a_d_l_x_g_p_u__driver_path.html',1,'DOX_IADLXGPU']]],
  ['driverversion_34',['DriverVersion',['../_d_o_x__i_a_d_l_x_g_p_u2__driver_version.html',1,'DOX_IADLXGPU2']]]
];
