var searchData=
[
  ['read_0',['Read',['../_d_o_x__i_a_d_l_x_i2_c__read.html',1,'DOX_IADLXI2C']]],
  ['receiving_20events_20notifications_1',['Receiving Events Notifications',['../domain_cpp_sample_globalsync.html',1,'Receiving Events Notifications'],['../domain_c_sample_globalsync.html',1,'Receiving Events Notifications']]],
  ['references_2',['ADLX SDK References',['../page_sdk.html',1,'']]],
  ['refreshrate_3',['RefreshRate',['../_d_o_x__i_a_d_l_x_display__refresh_rate.html',1,'DOX_IADLXDisplay']]],
  ['release_4',['Release',['../_d_o_x__i_a_d_l_x_interface__release.html',1,'DOX_IADLXInterface']]],
  ['remove3dsettingseventlistener_5',['Remove3DSettingsEventListener',['../_d_o_x__i_a_d_l_x3_d_settings_changed_handling__remove3_d_settings_event_listener.html',1,'DOX_IADLX3DSettingsChangedHandling']]],
  ['remove_5fback_6',['Remove_Back',['../_d_o_x__i_a_d_l_x_list__remove__back.html',1,'DOX_IADLXList']]],
  ['removedesktoplisteventlistener_7',['RemoveDesktopListEventListener',['../_d_o_x__i_a_d_l_x_desktop_changed_handling__remove_desktop_list_event_listener.html',1,'DOX_IADLXDesktopChangedHandling']]],
  ['removedisplay3dluteventlistener_8',['RemoveDisplay3DLUTEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__remove_display3_d_l_u_t_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['removedisplaygammaeventlistener_9',['RemoveDisplayGammaEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__remove_display_gamma_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['removedisplaygamuteventlistener_10',['RemoveDisplayGamutEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__remove_display_gamut_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['removedisplaylisteventlistener_11',['RemoveDisplayListEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__remove_display_list_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['removedisplaysettingseventlistener_12',['RemoveDisplaySettingsEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__remove_display_settings_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['removegpuappslisteventlistener_13',['RemoveGPUAppsListEventListener',['../_d_o_x__i_a_d_l_x_g_p_u_apps_list_changed_handling__remove_g_p_u_apps_list_event_listener.html',1,'DOX_IADLXGPUAppsListChangedHandling']]],
  ['removegpuslisteventlistener_14',['RemoveGPUsListEventListener',['../_d_o_x__i_a_d_l_x_g_p_us_changed_handling__remove_g_p_us_list_event_listener.html',1,'DOX_IADLXGPUsChangedHandling']]],
  ['removegputuningeventlistener_15',['RemoveGPUTuningEventListener',['../_d_o_x__i_a_d_l_x_g_p_u_tuning_changed_handling__remove_g_p_u_tuning_event_listener.html',1,'DOX_IADLXGPUTuningChangedHandling']]],
  ['removemultimediaeventlistener_16',['RemoveMultimediaEventListener',['../_d_o_x__i_a_d_l_x_multimedia_changed_handling__remove_multimedia_event_listener.html',1,'DOX_IADLXMultimediaChangedHandling']]],
  ['removepowertuningeventlistener_17',['RemovePowerTuningEventListener',['../_d_o_x__i_a_d_l_x_power_tuning_changed_handling__remove_power_tuning_event_listener.html',1,'DOX_IADLXPowerTuningChangedHandling']]],
  ['repeatedstartread_18',['RepeatedStartRead',['../_d_o_x__i_a_d_l_x_i2_c__repeated_start_read.html',1,'DOX_IADLXI2C']]],
  ['resetgammaramp_19',['ResetGammaRamp',['../_d_o_x__i_a_d_l_x_display_gamma__reset_gamma_ramp.html',1,'DOX_IADLXDisplayGamma']]],
  ['resetshadercache_20',['ResetShaderCache',['../_d_o_x__i_a_d_l_x3_d_reset_shader_cache__reset_shader_cache.html',1,'ResetShaderCache'],['../cpp__reset_shader_cache.html',1,'ResetShaderCache'],['../c__reset_shader_cache.html',1,'ResetShaderCache']]],
  ['resettofactory_21',['ResetToFactory',['../_d_o_x__i_a_d_l_x_g_p_u_tuning_services__reset_to_factory.html',1,'DOX_IADLXGPUTuningServices']]],
  ['revisionid_22',['RevisionId',['../_d_o_x__i_a_d_l_x_g_p_u__revision_id.html',1,'DOX_IADLXGPU']]],
  ['rsr_23',['RSR',['../cpp__r_s_r.html',1,'RSR'],['../c__r_s_r.html',1,'RSR']]]
];
