var searchData=
[
  ['a_20windows_20system_20service_20application_0',['Using ADLX in a Windows system service application',['../page_guide_usingservice.html',1,'page_guide_advanced']]],
  ['abortpoweroff_1',['AbortPowerOff',['../_d_o_x__i_a_d_l_x_g_p_u2__abort_power_off.html',1,'DOX_IADLXGPU2']]],
  ['acquire_2',['Acquire',['../_d_o_x__i_a_d_l_x_interface__acquire.html',1,'DOX_IADLXInterface']]],
  ['add3dsettingseventlistener_3',['Add3DSettingsEventListener',['../_d_o_x__i_a_d_l_x3_d_settings_changed_handling__add3_d_settings_event_listener.html',1,'DOX_IADLX3DSettingsChangedHandling']]],
  ['add_5fback_4',['Add_Back',['../_d_o_x__i_a_d_l_x3_d_fidelity_f_x_frame_gen_upgrade_ratio_option_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_application_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_desktop_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_display_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_display_resolution_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_manual_fan_tuning_state_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_manual_tuning_state_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_memory_timing_description_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_g_p_u_metrics_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_system_metrics_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_f_p_s_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_all_metrics_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_g_p_u_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_g_p_u2_list__add__back.html',1,'Add_Back'],['../_d_o_x__i_a_d_l_x_variable_graphics_memory_option_list__add__back.html',1,'Add_Back']]],
  ['adddesktoplisteventlistener_5',['AddDesktopListEventListener',['../_d_o_x__i_a_d_l_x_desktop_changed_handling__add_desktop_list_event_listener.html',1,'DOX_IADLXDesktopChangedHandling']]],
  ['adddisplay3dluteventlistener_6',['AddDisplay3DLUTEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display3_d_l_u_t_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaygammaeventlistener_7',['AddDisplayGammaEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_gamma_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaygamuteventlistener_8',['AddDisplayGamutEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_gamut_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaylisteventlistener_9',['AddDisplayListEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_list_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaysettingseventlistener_10',['AddDisplaySettingsEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_settings_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['addgpuappslisteventlistener_11',['AddGPUAppsListEventListener',['../_d_o_x__i_a_d_l_x_g_p_u_apps_list_changed_handling__add_g_p_u_apps_list_event_listener.html',1,'DOX_IADLXGPUAppsListChangedHandling']]],
  ['addgpuslisteventlistener_12',['AddGPUsListEventListener',['../_d_o_x__i_a_d_l_x_g_p_us_changed_handling__add_g_p_us_list_event_listener.html',1,'DOX_IADLXGPUsChangedHandling']]],
  ['addgputuningeventlistener_13',['AddGPUTuningEventListener',['../_d_o_x__i_a_d_l_x_g_p_u_tuning_changed_handling__add_g_p_u_tuning_event_listener.html',1,'DOX_IADLXGPUTuningChangedHandling']]],
  ['addmultimediaeventlistener_14',['AddMultimediaEventListener',['../_d_o_x__i_a_d_l_x_multimedia_changed_handling__add_multimedia_event_listener.html',1,'DOX_IADLXMultimediaChangedHandling']]],
  ['addpowertuningeventlistener_15',['AddPowerTuningEventListener',['../_d_o_x__i_a_d_l_x_power_tuning_changed_handling__add_power_tuning_event_listener.html',1,'DOX_IADLXPowerTuningChangedHandling']]],
  ['adladapterindexfromadlxgpu_16',['AdlAdapterIndexFromADLXGPU',['../_d_o_x__i_a_d_l_mapping__adl_adapter_index_from_a_d_l_x_g_p_u.html',1,'DOX_IADLMapping']]],
  ['adlidsfromadlxdesktop_17',['ADLIdsFromADLXDesktop',['../_d_o_x__i_a_d_l_mapping__a_d_l_ids_from_a_d_l_x_desktop.html',1,'DOX_IADLMapping']]],
  ['adlidsfromadlxdisplay_18',['ADLIdsFromADLXDisplay',['../_d_o_x__i_a_d_l_mapping__a_d_l_ids_from_a_d_l_x_display.html',1,'DOX_IADLMapping']]],
  ['adlx_19',['ADLX',['../page_guide_bindcsharp.html',1,'Building C# bindings for ADLX'],['../page_guide_bindjava.html',1,'Building Java bindings for ADLX'],['../page_guide_bindpy.html',1,'Building Python bindings for ADLX'],['../page_guide_bindrust.html',1,'Building Rust applications for ADLX'],['../page_programwithadlx.html',1,'Programming with ADLX'],['../page_guide_event.html',1,'Subscribing to Event Notifications using ADLX']]],
  ['adlx_20',['amd-adlx',['../rust_sample_amdadlx.html',1,'page_sample_rust']]],
  ['adlx_20functions_21',['ADLX Functions',['../funpage.html',1,'page_sdk']]],
  ['adlx_20helper_20functions_22',['ADLX Helper Functions',['../page__a_d_l_x_c_help.html',1,'page_ADLXHelps']]],
  ['adlx_20helpers_23',['ADLX Helpers',['../page__a_d_l_x_helps.html',1,'ADLX Helpers'],['../page_guide_init_help.html',1,'Initializing ADLX with the ADLX Helpers']]],
  ['adlx_20in_20a_20windows_20system_20service_20application_24',['Using ADLX in a Windows system service application',['../page_guide_usingservice.html',1,'page_guide_advanced']]],
  ['adlx_20in_20an_20application_25',['Using ADLX in an application',['../page_guide_use__a_d_l_x.html',1,'page_guide_qs']]],
  ['adlx_20interfaces_26',['ADLX Interfaces',['../page_interfaces.html',1,'page_sdk']]],
  ['adlx_20mcp_20servers_27',['ADLX MCP Servers',['../page_mcp.html',1,'page_programwithadlx']]],
  ['adlx_20programming_20guide_28',['ADLX Programming Guide',['../page_adlxprogrammingguide.html',1,'page_programwithadlx']]],
  ['adlx_20samples_29',['ADLX Samples',['../domain_sample_page.html',1,'page_programwithadlx']]],
  ['adlx_20sdk_20references_30',['ADLX SDK References',['../page_sdk.html',1,'']]],
  ['adlx_20with_20function_20pointers_31',['Initializing ADLX with function pointers',['../page_guide_init_pointer.html',1,'page_guide_qs']]],
  ['adlx_20with_20the_20adlx_20helpers_32',['Initializing ADLX with the ADLX Helpers',['../page_guide_init_help.html',1,'page_guide_qs']]],
  ['adlx_5fatomic_5fdec_33',['adlx_atomic_dec',['../adlx_atomic_dec.html',1,'funpage']]],
  ['adlx_5fatomic_5finc_34',['adlx_atomic_inc',['../adlx_atomic_inc.html',1,'funpage']]],
  ['adlx_5ffree_5flibrary_35',['adlx_free_library',['../adlx_free_library.html',1,'funpage']]],
  ['adlx_5fget_5fproc_5faddress_36',['adlx_get_proc_address',['../adlx_get_proc_address.html',1,'funpage']]],
  ['adlx_5fload_5flibrary_37',['adlx_load_library',['../adlx_load_library.html',1,'funpage']]],
  ['adlxcsharpbind_38',['ADLXCSharpBind',['../cs_sample_adlxcsharpbind.html',1,'page_sample_cs']]],
  ['adlxhelper_39',['ADLXHelper',['../page_cpp_help_new.html',1,'ADLXHelper'],['../page_cpp_help_delete.html',1,'~ADLXHelper']]],
  ['adlxhelper_20class_40',['ADLXHelper Class',['../page__a_d_l_x_cpp_help.html',1,'page_ADLXHelps']]],
  ['adlxhelper_5fgetadlmapping_41',['ADLXHelper_GetAdlMapping',['../page_c_help_a_d_l_x_helper__get_adl_mapping.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fgetsystemservices_42',['ADLXHelper_GetSystemServices',['../page_c_help_a_d_l_x_helper__get_system_services.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5finitialize_43',['ADLXHelper_Initialize',['../page_c_help_a_d_l_x_helper__initialize.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5finitializewithcalleradl_44',['ADLXHelper_InitializeWithCallerAdl',['../page_c_help_a_d_l_x_helper__initialize_with_caller_adl.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5finitializewithincompatibledriver_45',['ADLXHelper_InitializeWithIncompatibleDriver',['../page_c_help_a_d_l_x_helper__initialize_with_incompatible_driver.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fqueryfullversion_46',['ADLXHelper_QueryFullVersion',['../page_c_help_a_d_l_x_helper__query_full_version.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fqueryversion_47',['ADLXHelper_QueryVersion',['../page_c_help_a_d_l_x_helper__query_version.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fterminate_48',['ADLXHelper_Terminate',['../page_c_help_a_d_l_x_helper__terminate.html',1,'page_ADLXCHelp']]],
  ['adlxinitialize2_5ffn_49',['ADLXInitialize2_Fn',['../page__a_d_l_x_initialize2__fn.html',1,'funpage']]],
  ['adlxinitialize_5ffn_50',['ADLXInitialize_Fn',['../page__a_d_l_x_initialize__fn.html',1,'funpage']]],
  ['adlxinitializewithcalleradl_5ffn_51',['ADLXInitializeWithCallerAdl_Fn',['../page__a_d_l_x_initialize_with_caller_adl__fn.html',1,'funpage']]],
  ['adlxjavabind_52',['ADLXJavaBind',['../java_sample_adlxjavabind.html',1,'page_sample_java']]],
  ['adlxpybind_53',['ADLXPybind',['../py_sample_adlxpybind.html',1,'page_sample_py']]],
  ['adlxqueryfullversion_5ffn_54',['ADLXQueryFullVersion_Fn',['../page__a_d_l_x_query_full_version__fn.html',1,'funpage']]],
  ['adlxqueryversion_5ffn_55',['ADLXQueryVersion_Fn',['../page__a_d_l_x_query_version__fn.html',1,'funpage']]],
  ['adlxterminate_5ffn_56',['ADLXTerminate_Fn',['../page__a_d_l_x_terminate__fn.html',1,'funpage']]],
  ['advanced_20configurations_57',['Advanced Configurations',['../page_guide_advanced.html',1,'page_adlxprogrammingguide']]],
  ['afmf_58',['AFMF',['../cpp__a_f_m_f.html',1,'AFMF'],['../c__a_f_m_f.html',1,'AFMF']]],
  ['amd_20adlx_59',['amd-adlx',['../rust_sample_amdadlx.html',1,'page_sample_rust']]],
  ['amd_20device_20library_20extra_60',['AMD Device Library eXtra',['../index.html',1,'']]],
  ['amdsoftwareedition_61',['AMDSoftwareEdition',['../_d_o_x__i_a_d_l_x_g_p_u2__a_m_d_software_edition.html',1,'DOX_IADLXGPU2']]],
  ['amdsoftwarereleasedate_62',['AMDSoftwareReleaseDate',['../_d_o_x__i_a_d_l_x_g_p_u2__a_m_d_software_release_date.html',1,'DOX_IADLXGPU2']]],
  ['amdsoftwareversion_63',['AMDSoftwareVersion',['../_d_o_x__i_a_d_l_x_g_p_u2__a_m_d_software_version.html',1,'DOX_IADLXGPU2']]],
  ['amdwindowsdriverversion_64',['AMDWindowsDriverVersion',['../_d_o_x__i_a_d_l_x_g_p_u2__a_m_d_windows_driver_version.html',1,'DOX_IADLXGPU2']]],
  ['an_20application_65',['Using ADLX in an application',['../page_guide_use__a_d_l_x.html',1,'page_guide_qs']]],
  ['and_20compliance_20disclaimers_66',['Legal Information and Compliance/Disclaimers',['../page_legal.html',1,'']]],
  ['anisotropicfiltering_67',['AnisotropicFiltering',['../cpp__anisotropic_filtering.html',1,'AnisotropicFiltering'],['../c__anisotropic_filtering.html',1,'AnisotropicFiltering']]],
  ['antialiasing_68',['AntiAliasing',['../cpp__anti_aliasing.html',1,'AntiAliasing'],['../c__anti_aliasing.html',1,'AntiAliasing']]],
  ['antilag_69',['AntiLag',['../cpp__anti_lag.html',1,'AntiLag'],['../c__anti_lag.html',1,'AntiLag']]],
  ['application_70',['application',['../page_guide_usingservice.html',1,'Using ADLX in a Windows system service application'],['../page_guide_use__a_d_l_x.html',1,'Using ADLX in an application']]],
  ['applications_20for_20adlx_71',['Building Rust applications for ADLX',['../page_guide_bindrust.html',1,'page_guide_qs']]],
  ['asicfamilytype_72',['ASICFamilyType',['../_d_o_x__i_a_d_l_x_g_p_u__a_s_i_c_family_type.html',1,'DOX_IADLXGPU']]],
  ['asynceventhandling_73',['AsyncEventHandling',['../cpp_sample__async_event_handling.html',1,'AsyncEventHandling'],['../c_sample__async_event_handling.html',1,'AsyncEventHandling']]],
  ['at_74',['At',['../_d_o_x__i_a_d_l_x3_d_fidelity_f_x_frame_gen_upgrade_ratio_option_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_application_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_desktop_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_display_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_display_resolution_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_manual_fan_tuning_state_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_manual_tuning_state_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_memory_timing_description_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_g_p_u_metrics_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_system_metrics_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_f_p_s_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_all_metrics_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_g_p_u_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_g_p_u2_list__at.html',1,'At'],['../_d_o_x__i_a_d_l_x_variable_graphics_memory_option_list__at.html',1,'At']]]
];
