var searchData=
[
  ['acquire_1242',['Acquire',['../_d_o_x__i_a_d_l_x_interface__acquire.html',1,'DOX_IADLXInterface']]],
  ['add3dsettingseventlistener_1243',['Add3DSettingsEventListener',['../_d_o_x__i_a_d_l_x3_d_settings_changed_handling__add3_d_settings_event_listener.html',1,'DOX_IADLX3DSettingsChangedHandling']]],
  ['add_5fback_1244',['Add_Back',['../_d_o_x__i_a_d_l_x_all_metrics_list__add__back.html',1,'DOX_IADLXAllMetricsList'],['../_d_o_x__i_a_d_l_x_desktop_list__add__back.html',1,'DOX_IADLXDesktopList'],['../_d_o_x__i_a_d_l_x_display_list__add__back.html',1,'DOX_IADLXDisplayList'],['../_d_o_x__i_a_d_l_x_display_resolution_list__add__back.html',1,'DOX_IADLXDisplayResolutionList'],['../_d_o_x__i_a_d_l_x_f_p_s_list__add__back.html',1,'DOX_IADLXFPSList'],['../_d_o_x__i_a_d_l_x_g_p_u_list__add__back.html',1,'DOX_IADLXGPUList'],['../_d_o_x__i_a_d_l_x_g_p_u_metrics_list__add__back.html',1,'DOX_IADLXGPUMetricsList'],['../_d_o_x__i_a_d_l_x_list__add__back.html',1,'DOX_IADLXList'],['../_d_o_x__i_a_d_l_x_manual_fan_tuning_state_list__add__back.html',1,'DOX_IADLXManualFanTuningStateList'],['../_d_o_x__i_a_d_l_x_manual_tuning_state_list__add__back.html',1,'DOX_IADLXManualTuningStateList'],['../_d_o_x__i_a_d_l_x_memory_timing_description_list__add__back.html',1,'DOX_IADLXMemoryTimingDescriptionList'],['../_d_o_x__i_a_d_l_x_system_metrics_list__add__back.html',1,'DOX_IADLXSystemMetricsList']]],
  ['adddesktoplisteventlistener_1245',['AddDesktopListEventListener',['../_d_o_x__i_a_d_l_x_desktop_changed_handling__add_desktop_list_event_listener.html',1,'DOX_IADLXDesktopChangedHandling']]],
  ['adddisplay3dluteventlistener_1246',['AddDisplay3DLUTEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display3_d_l_u_t_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaygammaeventlistener_1247',['AddDisplayGammaEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_gamma_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaygamuteventlistener_1248',['AddDisplayGamutEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_gamut_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaylisteventlistener_1249',['AddDisplayListEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_list_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['adddisplaysettingseventlistener_1250',['AddDisplaySettingsEventListener',['../_d_o_x__i_a_d_l_x_display_changed_handling__add_display_settings_event_listener.html',1,'DOX_IADLXDisplayChangedHandling']]],
  ['addgpuslisteventlistener_1251',['AddGPUsListEventListener',['../_d_o_x__i_a_d_l_x_g_p_us_changed_handling__add_g_p_us_list_event_listener.html',1,'DOX_IADLXGPUsChangedHandling']]],
  ['addgputuningeventlistener_1252',['AddGPUTuningEventListener',['../_d_o_x__i_a_d_l_x_g_p_u_tuning_changed_handling__add_g_p_u_tuning_event_listener.html',1,'DOX_IADLXGPUTuningChangedHandling']]],
  ['adladapterindexfromadlxgpu_1253',['AdlAdapterIndexFromADLXGPU',['../_d_o_x__i_a_d_l_mapping__adl_adapter_index_from_a_d_l_x_g_p_u.html',1,'DOX_IADLMapping']]],
  ['adlidsfromadlxdesktop_1254',['ADLIdsFromADLXDesktop',['../_d_o_x__i_a_d_l_mapping__a_d_l_ids_from_a_d_l_x_desktop.html',1,'DOX_IADLMapping']]],
  ['adlidsfromadlxdisplay_1255',['ADLIdsFromADLXDisplay',['../_d_o_x__i_a_d_l_mapping__a_d_l_ids_from_a_d_l_x_display.html',1,'DOX_IADLMapping']]],
  ['adlx_20functions_1256',['ADLX Functions',['../funpage.html',1,'page_sdk']]],
  ['adlx_20helper_20functions_1257',['ADLX Helper Functions',['../page__a_d_l_x_c_help.html',1,'page_ADLXHelps']]],
  ['adlx_20helpers_1258',['ADLX Helpers',['../page__a_d_l_x_helps.html',1,'page_sdk']]],
  ['adlx_20interfaces_1259',['ADLX Interfaces',['../page_interfaces.html',1,'page_sdk']]],
  ['adlx_20programming_20guide_1260',['ADLX Programming Guide',['../page_adlxprogrammingguide.html',1,'page_programwithadlx']]],
  ['adlx_20samples_1261',['ADLX Samples',['../sample_page.html',1,'page_programwithadlx']]],
  ['adlx_20sdk_20references_1262',['ADLX SDK References',['../page_sdk.html',1,'']]],
  ['adlx_5fatomic_5fdec_1263',['adlx_atomic_dec',['../adlx_atomic_dec.html',1,'funpage']]],
  ['adlx_5fatomic_5finc_1264',['adlx_atomic_inc',['../adlx_atomic_inc.html',1,'funpage']]],
  ['adlx_5ffree_5flibrary_1265',['adlx_free_library',['../adlx_free_library.html',1,'funpage']]],
  ['adlx_5fget_5fproc_5faddress_1266',['adlx_get_proc_address',['../adlx_get_proc_address.html',1,'funpage']]],
  ['adlx_5fload_5flibrary_1267',['adlx_load_library',['../adlx_load_library.html',1,'funpage']]],
  ['adlxcsharpbind_1268',['ADLXCSharpBind',['../cs_sample_adlxcsharpbind.html',1,'cs_samples_more']]],
  ['adlxhelper_1269',['ADLXHelper',['../page_cpp_help_new.html',1,'page_ADLXCppHelp']]],
  ['adlxhelper_20class_1270',['ADLXHelper Class',['../page__a_d_l_x_cpp_help.html',1,'page_ADLXHelps']]],
  ['adlxhelper_5fgetadlmapping_1271',['ADLXHelper_GetAdlMapping',['../page_c_help_a_d_l_x_helper__get_adl_mapping.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fgetsystemservices_1272',['ADLXHelper_GetSystemServices',['../page_c_help_a_d_l_x_helper__get_system_services.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5finitialize_1273',['ADLXHelper_Initialize',['../page_c_help_a_d_l_x_helper__initialize.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5finitializewithcalleradl_1274',['ADLXHelper_InitializeWithCallerAdl',['../page_c_help_a_d_l_x_helper__initialize_with_caller_adl.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5finitializewithincompatibledriver_1275',['ADLXHelper_InitializeWithIncompatibleDriver',['../page_c_help_a_d_l_x_helper__initialize_with_incompatible_driver.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fqueryfullversion_1276',['ADLXHelper_QueryFullVersion',['../page_c_help_a_d_l_x_helper__query_full_version.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fqueryversion_1277',['ADLXHelper_QueryVersion',['../page_c_help_a_d_l_x_helper__query_version.html',1,'page_ADLXCHelp']]],
  ['adlxhelper_5fterminate_1278',['ADLXHelper_Terminate',['../page_c_help_a_d_l_x_helper__terminate.html',1,'page_ADLXCHelp']]],
  ['adlxinitialize_5ffn_1279',['ADLXInitialize_Fn',['../page__a_d_l_x_initialize__fn.html',1,'funpage']]],
  ['adlxinitializewithcalleradl_5ffn_1280',['ADLXInitializeWithCallerAdl_Fn',['../page__a_d_l_x_initialize_with_caller_adl__fn.html',1,'funpage']]],
  ['adlxjavabind_1281',['ADLXJavaBind',['../java_sample_adlxjavabind.html',1,'java_samples_more']]],
  ['adlxpybind_1282',['ADLXPybind',['../py_sample_adlxpybind.html',1,'py_samples_more']]],
  ['adlxqueryfullversion_5ffn_1283',['ADLXQueryFullVersion_Fn',['../page__a_d_l_x_query_full_version__fn.html',1,'funpage']]],
  ['adlxqueryversion_5ffn_1284',['ADLXQueryVersion_Fn',['../page__a_d_l_x_query_version__fn.html',1,'funpage']]],
  ['adlxterminate_5ffn_1285',['ADLXTerminate_Fn',['../page__a_d_l_x_terminate__fn.html',1,'funpage']]],
  ['advanced_20configurations_1286',['Advanced Configurations',['../page_guide_advanced.html',1,'page_adlxprogrammingguide']]],
  ['amd_20device_20library_20extra_1287',['AMD Device Library eXtra',['../index.html',1,'']]],
  ['anisotropicfiltering_1288',['AnisotropicFiltering',['../c__anisotropic_filtering.html',1,'c_sample_3DGraphics'],['../cpp__anisotropic_filtering.html',1,'cpp_sample_3DGraphics']]],
  ['antialiasing_1289',['AntiAliasing',['../c__anti_aliasing.html',1,'c_sample_3DGraphics'],['../cpp__anti_aliasing.html',1,'cpp_sample_3DGraphics']]],
  ['antilag_1290',['AntiLag',['../c__anti_lag.html',1,'c_sample_3DGraphics'],['../cpp__anti_lag.html',1,'cpp_sample_3DGraphics']]],
  ['asicfamilytype_1291',['ASICFamilyType',['../_d_o_x__i_a_d_l_x_g_p_u__a_s_i_c_family_type.html',1,'DOX_IADLXGPU']]],
  ['asynceventhandling_1292',['AsyncEventHandling',['../c_sample__async_event_handling.html',1,'c_sample_globalsync'],['../cpp_sample__async_event_handling.html',1,'cpp_sample_globalsync']]],
  ['at_1293',['At',['../_d_o_x__i_a_d_l_x_all_metrics_list__at.html',1,'DOX_IADLXAllMetricsList'],['../_d_o_x__i_a_d_l_x_desktop_list__at.html',1,'DOX_IADLXDesktopList'],['../_d_o_x__i_a_d_l_x_display_list__at.html',1,'DOX_IADLXDisplayList'],['../_d_o_x__i_a_d_l_x_display_resolution_list__at.html',1,'DOX_IADLXDisplayResolutionList'],['../_d_o_x__i_a_d_l_x_f_p_s_list__at.html',1,'DOX_IADLXFPSList'],['../_d_o_x__i_a_d_l_x_g_p_u_list__at.html',1,'DOX_IADLXGPUList'],['../_d_o_x__i_a_d_l_x_g_p_u_metrics_list__at.html',1,'DOX_IADLXGPUMetricsList'],['../_d_o_x__i_a_d_l_x_list__at.html',1,'DOX_IADLXList'],['../_d_o_x__i_a_d_l_x_manual_fan_tuning_state_list__at.html',1,'DOX_IADLXManualFanTuningStateList'],['../_d_o_x__i_a_d_l_x_manual_tuning_state_list__at.html',1,'DOX_IADLXManualTuningStateList'],['../_d_o_x__i_a_d_l_x_memory_timing_description_list__at.html',1,'DOX_IADLXMemoryTimingDescriptionList'],['../_d_o_x__i_a_d_l_x_system_metrics_list__at.html',1,'DOX_IADLXSystemMetricsList']]]
];
