[package]
name = "variable-graphics-memory"
description = "ADLX Rust sample: query Variable Graphics Memory settings"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "VariableGraphicsMemory"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
