[package]
name = "display-events"
description = "ADLX Rust sample: handle notifications about display list changes"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "DisplayEvents"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
