[package]
name = "display-3dlut"
description = "ADLX Rust sample: query display 3D-LUT source color enhancement (SCE) presets"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "Display3DLUT"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
