[workspace]
resolver = "2"
members = [
    "amd-adlx",
    "DisplayInfo",
    "DisplayEvents",
    "GPUInfo",
    "PerfGPUMetrics",
    "Log",
    "AntiLag",
    "SmartAccessMemory",
    "PerfSystemMetrics",
    "PerfFPSMetrics",
    "ManualFanTuning",
    "DisplayFreeSync",
    "DisplayVSR",
    "DisplayGPUScaling",
    "DisplayIntegerScaling",
    "EnhancedSync",
    "Boost",
    "Chill",
    "ImageSharpening",
    "RSR",
    "AnisotropicFiltering",
    "Tessellation",
    "ResetShaderCache",
    "AntiAliasing",
    "MorphologicAntiAliasing",
    "WaitForVerticalRefresh",
    "FRTC",
    "DisplayHDCP",
    "DisplayScalingMode",
    "DisplayColorDepth",
    "DisplayPixelFormat",
    "DisplayVariBright",
    "Desktops",
    "SmartShiftMax",
    "VideoSuperResolution",
    "Videoupscale",
    "VariableGraphicsMemory",
    "ManualPowerTuning",
    "GPUPresetTuning",
    "DisplayBlanking",
    "AFMF",
    "PrimaryAdapter",
    "InvalidObject",
    "DisplayDynamicRefreshRateControl",
    "DisplayFreeSyncColorAccuracy",
    "DisplayConnectivityExperience",
    "DisplayCustomColor",
    "DisplaySDRToHDR",
    "DisplayCustomResolution",
    "GPUAutoTuning",
    "I2C",
    "ManualGraphicsTuning",
    "ManualVRAMTuning",
    "FidelityFXSuperResolution",
    "DesktopsEvent",
    "Display3DLUT",
    "3DSettingsEvent",
    "SmartShiftEco",
    "DisplayGamut",
    "DisplayGamma",
    "Eyefinity",
    "SyncGPUTuning",
    "SyncPowerTuning",
    "SyncMultimedia",
    "SyncDisplayReceive",
    "GPUStressTest",
    "FidelityFXFrameGenUpgrade",
    "smoke-tests",
]

[workspace.package]
version = "1.0.0"
edition = "2021"
license = "MIT"
publish = false
