[package]
name = "desktops"
description = "ADLX Rust sample: enumerate desktops and print their information"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "Desktops"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
