[package]
name = "sync-power-tuning"
description = "ADLX Rust sample: receive synchronous power tuning change notifications"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "SyncPowerTuning"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
