[package]
name = "sync-display-receive"
description = "ADLX Rust sample: receive synchronous display change notifications"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "SyncDisplayReceive"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
