//
// Copyright Advanced Micro Devices, Inc. All rights reserved.
//
//-------------------------------------------------------------------------------------------------

#include "bind_common.h"

void bind_enums(py::module_& m)
{
    // Define the objects that get exposed to python
    // ADLX_RESULT
    py::enum_<ADLX_RESULT>(m, "ADLX_RESULT")
        .value("ADLX_OK", ADLX_RESULT::ADLX_OK)
        .value("ADLX_ALREADY_ENABLED", ADLX_RESULT::ADLX_ALREADY_ENABLED)
        .value("ADLX_ALREADY_INITIALIZED", ADLX_RESULT::ADLX_ALREADY_INITIALIZED)
        .value("ADLX_FAIL", ADLX_RESULT::ADLX_FAIL)
        .value("ADLX_INVALID_ARGS", ADLX_RESULT::ADLX_INVALID_ARGS)
        .value("ADLX_BAD_VER", ADLX_RESULT::ADLX_BAD_VER)
        .value("ADLX_UNKNOWN_INTERFACE", ADLX_RESULT::ADLX_UNKNOWN_INTERFACE)
        .value("ADLX_TERMINATED", ADLX_RESULT::ADLX_TERMINATED)
        .value("ADLX_ADL_INIT_ERROR", ADLX_RESULT::ADLX_ADL_INIT_ERROR)
        .value("ADLX_NOT_FOUND", ADLX_RESULT::ADLX_NOT_FOUND)
        .value("ADLX_INVALID_OBJECT", ADLX_RESULT::ADLX_INVALID_OBJECT)
        .value("ADLX_ORPHAN_OBJECTS", ADLX_RESULT::ADLX_ORPHAN_OBJECTS)
        .value("ADLX_NOT_SUPPORTED", ADLX_RESULT::ADLX_NOT_SUPPORTED)
        .value("ADLX_PENDING_OPERATION", ADLX_RESULT::ADLX_PENDING_OPERATION)
        .value("ADLX_GPU_INACTIVE", ADLX_RESULT::ADLX_GPU_INACTIVE)
        .value("ADLX_GPU_IN_USE", ADLX_RESULT::ADLX_GPU_IN_USE)
        .value("ADLX_TIMEOUT_OPERATION", ADLX_RESULT::ADLX_TIMEOUT_OPERATION)
        .value("ADLX_NOT_ACTIVE", ADLX_RESULT::ADLX_NOT_ACTIVE)
        .value("ADLX_RESET_NEEDED", ADLX_RESULT::ADLX_RESET_NEEDED)
        .export_values();

    // ADLX_DISPLAY_TYPE
    py::enum_<ADLX_DISPLAY_TYPE>(m, "ADLX_DISPLAY_TYPE")
        .value("DISPLAY_TYPE_UNKOWN", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_UNKOWN)
        .value("DISPLAY_TYPE_MONITOR", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_MONITOR)
        .value("DISPLAY_TYPE_TELEVISION", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_TELEVISION)
        .value("DISPLAY_TYPE_LCD_PANEL", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_LCD_PANEL)
        .value("DISPLAY_TYPE_DIGITAL_FLAT_PANEL", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_DIGITAL_FLAT_PANEL)
        .value("DISPLAY_TYPE_COMPONENT_VIDEO", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_COMPONENT_VIDEO)
        .value("DISPLAY_TYPE_PROJECTOR", ADLX_DISPLAY_TYPE::DISPLAY_TYPE_PROJECTOR)
        .export_values();

    // ADLX_DISPLAY_CONNECTOR_TYPE
    py::enum_<ADLX_DISPLAY_CONNECTOR_TYPE>(m, "ADLX_DISPLAY_CONNECTOR_TYPE")
        .value("DISPLAY_CONTYPE_UNKNOWN", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_UNKNOWN)
        .value("DISPLAY_CONTYPE_VGA", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_VGA)
        .value("DISPLAY_CONTYPE_DVI_D", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_DVI_D)
        .value("DISPLAY_CONTYPE_DVI_I", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_DVI_I)
        .value("DISPLAY_CONTYPE_CVDONGLE_NTSC", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_CVDONGLE_NTSC)
        .value("DISPLAY_CONTYPE_CVDONGLE_JPN", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_CVDONGLE_JPN)
        .value("DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN)
        .value("DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC)
        .value("DISPLAY_CONTYPE_HDMI_TYPE_A", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_HDMI_TYPE_A)
        .value("DISPLAY_CONTYPE_HDMI_TYPE_B", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_HDMI_TYPE_B)
        .value("DISPLAY_CONTYPE_SVIDEO", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_SVIDEO)
        .value("DISPLAY_CONTYPE_COMPOSITE", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_COMPOSITE)
        .value("DISPLAY_CONTYPE_RCA_3COMPONENT", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_RCA_3COMPONENT)
        .value("DISPLAY_CONTYPE_DISPLAYPORT", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_DISPLAYPORT)
        .value("DISPLAY_CONTYPE_EDP", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_EDP)
        .value("DISPLAY_CONTYPE_WIRELESSDISPLAY", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_WIRELESSDISPLAY)
        .value("DISPLAY_CONTYPE_USB_TYPE_C", ADLX_DISPLAY_CONNECTOR_TYPE::DISPLAY_CONTYPE_USB_TYPE_C)
        .export_values();

    // ADLX_DISPLAY_SCAN_TYPE
    py::enum_<ADLX_DISPLAY_SCAN_TYPE>(m, "ADLX_DISPLAY_SCAN_TYPE")
        .value("PROGRESSIVE", ADLX_DISPLAY_SCAN_TYPE::PROGRESSIVE)
        .value("INTERLACED", ADLX_DISPLAY_SCAN_TYPE::INTERLACED)
        .export_values();

    // ADLX_TIMING_STANDARD
    py::enum_<ADLX_TIMING_STANDARD>(m, "ADLX_TIMING_STANDARD")
        .value("CVT", ADLX_TIMING_STANDARD::CVT)
        .value("CVT_RB", ADLX_TIMING_STANDARD::CVT_RB)
        .value("GTF", ADLX_TIMING_STANDARD::GTF)
        .value("DMT", ADLX_TIMING_STANDARD::DMT)
        .value("MANUAL", ADLX_TIMING_STANDARD::MANUAL)
        .export_values();

    py::enum_<ADLX_ASIC_FAMILY_TYPE>(m, "ADLX_ASIC_FAMILY_TYPE")
        .value("ASIC_UNDEFINED", ADLX_ASIC_FAMILY_TYPE::ASIC_UNDEFINED)
        .value("ASIC_RADEON", ADLX_ASIC_FAMILY_TYPE::ASIC_RADEON)
        .value("ASIC_FIREPRO", ADLX_ASIC_FAMILY_TYPE::ASIC_FIREPRO)
        .value("ASIC_FIREMV", ADLX_ASIC_FAMILY_TYPE::ASIC_FIREMV)
        .value("ASIC_FIRESTREAM", ADLX_ASIC_FAMILY_TYPE::ASIC_FIRESTREAM)
        .value("ASIC_FUSION", ADLX_ASIC_FAMILY_TYPE::ASIC_FUSION)
        .value("ASIC_EMBEDDED", ADLX_ASIC_FAMILY_TYPE::ASIC_EMBEDDED)
        .export_values();

    py::enum_<ADLX_GPU_TYPE>(m, "ADLX_GPU_TYPE")
        .value("GPUTYPE_UNDEFINED", ADLX_GPU_TYPE::GPUTYPE_UNDEFINED)
        .value("GPUTYPE_INTEGRATED", ADLX_GPU_TYPE::GPUTYPE_INTEGRATED)
        .value("GPUTYPE_DISCRETE", ADLX_GPU_TYPE::GPUTYPE_DISCRETE)
        .export_values();

    py::enum_<ADLX_LOG_DESTINATION>(m, "ADLX_LOG_DESTINATION")
        .value("LOCALFILE", ADLX_LOG_DESTINATION::LOCALFILE)
        .value("DBGVIEW", ADLX_LOG_DESTINATION::DBGVIEW)
        .value("APPLICATION", ADLX_LOG_DESTINATION::APPLICATION)
        .export_values();

    py::enum_<ADLX_LOG_SEVERITY>(m, "ADLX_LOG_SEVERITY")
        .value("LDEBUG", ADLX_LOG_SEVERITY::LDEBUG)
        .value("LWARNING", ADLX_LOG_SEVERITY::LWARNING)
        .value("LERROR", ADLX_LOG_SEVERITY::LERROR)
        .export_values();
    
    py::enum_<ADLX_ANISOTROPIC_FILTERING_LEVEL>(m, "ADLX_ANISOTROPIC_FILTERING_LEVEL")
        .value("AF_LEVEL_INVALID", ADLX_ANISOTROPIC_FILTERING_LEVEL::AF_LEVEL_INVALID)
        .value("AF_LEVEL_X2", ADLX_ANISOTROPIC_FILTERING_LEVEL::AF_LEVEL_X2)
        .value("AF_LEVEL_X4", ADLX_ANISOTROPIC_FILTERING_LEVEL::AF_LEVEL_X4)
        .value("AF_LEVEL_X8", ADLX_ANISOTROPIC_FILTERING_LEVEL::AF_LEVEL_X8)
        .value("AF_LEVEL_X16", ADLX_ANISOTROPIC_FILTERING_LEVEL::AF_LEVEL_X16)
        .export_values();

    py::enum_<ADLX_ANTI_ALIASING_LEVEL>(m, "ADLX_ANTI_ALIASING_LEVEL")
        .value("AA_LEVEL_INVALID", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_INVALID)
        .value("AA_LEVEL_2X", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_2X)
        .value("AA_LEVEL_2XEQ", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_2XEQ)
        .value("AA_LEVEL_4X", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_4X)
        .value("AA_LEVEL_4XEQ", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_4XEQ)
        .value("AA_LEVEL_8X", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_8X)
        .value("AA_LEVEL_8XEQ", ADLX_ANTI_ALIASING_LEVEL::AA_LEVEL_8XEQ)
        .export_values();

    py::enum_<ADLX_ANTI_ALIASING_METHOD>(m, "ADLX_ANTI_ALIASING_METHOD")
        .value("AA_METHOD_MULTISAMPLING", ADLX_ANTI_ALIASING_METHOD::AA_METHOD_MULTISAMPLING)
        .value("AA_METHOD_ADAPTIVE_MULTISAMPLING", ADLX_ANTI_ALIASING_METHOD::AA_METHOD_ADAPTIVE_MULTISAMPLING)
        .value("AA_METHOD_SUPERSAMPLING", ADLX_ANTI_ALIASING_METHOD::AA_METHOD_SUPERSAMPLING)
        .export_values();

    py::enum_<ADLX_ANTI_ALIASING_MODE>(m, "ADLX_ANTI_ALIASING_MODE")
        .value("AA_MODE_USE_APP_SETTINGS", ADLX_ANTI_ALIASING_MODE::AA_MODE_USE_APP_SETTINGS)
        .value("AA_MODE_ENHANCE_APP_SETTINGS", ADLX_ANTI_ALIASING_MODE::AA_MODE_ENHANCE_APP_SETTINGS)
        .value("AA_MODE_OVERRIDE_APP_SETTINGS", ADLX_ANTI_ALIASING_MODE::AA_MODE_OVERRIDE_APP_SETTINGS)
        .export_values();

    py::enum_<ADLX_TESSELLATION_LEVEL>(m, "ADLX_TESSELLATION_LEVEL")
        .value("T_LEVEL_OFF", ADLX_TESSELLATION_LEVEL::T_LEVEL_OFF)
        .value("T_LEVEL_2X", ADLX_TESSELLATION_LEVEL::T_LEVEL_2X)
        .value("T_LEVEL_4X", ADLX_TESSELLATION_LEVEL::T_LEVEL_4X)
        .value("T_LEVEL_6X", ADLX_TESSELLATION_LEVEL::T_LEVEL_6X)
        .value("T_LEVEL_8X", ADLX_TESSELLATION_LEVEL::T_LEVEL_8X)
        .value("T_LEVEL_16X", ADLX_TESSELLATION_LEVEL::T_LEVEL_16X)
        .value("T_LEVEL_32X", ADLX_TESSELLATION_LEVEL::T_LEVEL_32X)
        .value("T_LEVEL_64X", ADLX_TESSELLATION_LEVEL::T_LEVEL_64X)
        .export_values();

    py::enum_<ADLX_TESSELLATION_MODE>(m, "ADLX_TESSELLATION_MODE")
        .value("T_MODE_AMD_OPTIMIZED", ADLX_TESSELLATION_MODE::T_MODE_AMD_OPTIMIZED)
        .value("T_MODE_USE_APP_SETTINGS", ADLX_TESSELLATION_MODE::T_MODE_USE_APP_SETTINGS)
        .value("T_MODE_OVERRIDE_APP_SETTINGS", ADLX_TESSELLATION_MODE::T_MODE_OVERRIDE_APP_SETTINGS)
        .export_values();

    py::enum_<ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE>(m, "ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE")
        .value("WFVR_ALWAYS_OFF", ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE::WFVR_ALWAYS_OFF)
        .value("WFVR_OFF_UNLESS_APP_SPECIFIES", ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE::WFVR_OFF_UNLESS_APP_SPECIFIES)
        .value("WFVR_ON_UNLESS_APP_SPECIFIES", ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE::WFVR_ON_UNLESS_APP_SPECIFIES)
        .value("WFVR_ALWAYS_ON", ADLX_WAIT_FOR_VERTICAL_REFRESH_MODE::WFVR_ALWAYS_ON)
        .export_values();

    py::enum_<ADLX_ORIENTATION>(m, "ADLX_ORIENTATION")
        .value("ORIENTATION_LANDSCAPE", ADLX_ORIENTATION::ORIENTATION_LANDSCAPE)
        .value("ORIENTATION_PORTRAIT", ADLX_ORIENTATION::ORIENTATION_PORTRAIT)
        .value("ORIENTATION_LANDSCAPE_FLIPPED", ADLX_ORIENTATION::ORIENTATION_LANDSCAPE_FLIPPED)
        .value("ORIENTATION_PORTRAIT_FLIPPED", ADLX_ORIENTATION::ORIENTATION_PORTRAIT_FLIPPED)
        .export_values();

    py::enum_<ADLX_DESKTOP_TYPE>(m, "ADLX_DESKTOP_TYPE")
        .value("DESKTOP_SINGLE", ADLX_DESKTOP_TYPE::DESKTOP_SINGLE)
        .value("DESKTOP_DUPLCATE", ADLX_DESKTOP_TYPE::DESKTOP_DUPLCATE)
        .value("DESKTOP_EYEFINITY", ADLX_DESKTOP_TYPE::DESKTOP_EYEFINITY)
        .export_values();
    
    py::enum_<ADLX_3DLUT_TRANSFER_FUNCTION>(m, "ADLX_3DLUT_TRANSFER_FUNCTION")
        .value("TF_SRGB", ADLX_3DLUT_TRANSFER_FUNCTION::TF_SRGB)
        .value("TF_PQ", ADLX_3DLUT_TRANSFER_FUNCTION::TF_PQ)
        .value("TF_G22", ADLX_3DLUT_TRANSFER_FUNCTION::TF_G22)
        .export_values();

    py::enum_<ADLX_3DLUT_COLORSPACE>(m, "ADLX_3DLUT_COLORSPACE")
        .value("CS_SRGB", ADLX_3DLUT_COLORSPACE::CS_SRGB)
        .value("CS_BT2020", ADLX_3DLUT_COLORSPACE::CS_BT2020)
        .value("CS_DCIP3", ADLX_3DLUT_COLORSPACE::CS_DCIP3)
        .value("CS_NATIVE", ADLX_3DLUT_COLORSPACE::CS_NATIVE)
        .export_values();

    py::enum_<ADLX_COLOR_DEPTH>(m, "ADLX_COLOR_DEPTH")
        .value("BPC_6", ADLX_COLOR_DEPTH::BPC_6)
        .value("BPC_8", ADLX_COLOR_DEPTH::BPC_8)
        .value("BPC_10", ADLX_COLOR_DEPTH::BPC_10)
        .value("BPC_12", ADLX_COLOR_DEPTH::BPC_12)
        .value("BPC_14", ADLX_COLOR_DEPTH::BPC_14)
        .value("BPC_16", ADLX_COLOR_DEPTH::BPC_16)
        .export_values();

    py::enum_<ADLX_PIXEL_FORMAT>(m, "ADLX_PIXEL_FORMAT")
        .value("FORMAT_UNKNOWN", ADLX_PIXEL_FORMAT::FORMAT_UNKNOWN)
        .value("RGB_444_FULL", ADLX_PIXEL_FORMAT::RGB_444_FULL)
        .value("YCBCR_444", ADLX_PIXEL_FORMAT::YCBCR_444)
        .value("YCBCR_422", ADLX_PIXEL_FORMAT::YCBCR_422)
        .value("RGB_444_LIMITED", ADLX_PIXEL_FORMAT::RGB_444_LIMITED)
        .value("YCBCR_420", ADLX_PIXEL_FORMAT::YCBCR_420)
        .export_values();

    py::enum_<ADLX_SCALE_MODE>(m, "ADLX_SCALE_MODE")
        .value("PRESERVE_ASPECT_RATIO", ADLX_SCALE_MODE::PRESERVE_ASPECT_RATIO)
        .value("FULL_PANEL", ADLX_SCALE_MODE::FULL_PANEL)
        .value("CENTERED", ADLX_SCALE_MODE::CENTERED)
        .export_values();

    py::enum_<ADLX_I2C_LINE>(m, "ADLX_I2C_LINE")
        .value("I2C_LINE_OEM", ADLX_I2C_LINE::I2C_LINE_OEM)
        .value("I2C_LINE_OD_CONTROL", ADLX_I2C_LINE::I2C_LINE_OD_CONTROL)
        .value("I2C_LINE_OEM2", ADLX_I2C_LINE::I2C_LINE_OEM2)
        .value("I2C_LINE_OEM3", ADLX_I2C_LINE::I2C_LINE_OEM3)
        .value("I2C_LINE_OEM4", ADLX_I2C_LINE::I2C_LINE_OEM4)
        .value("I2C_LINE_OEM5", ADLX_I2C_LINE::I2C_LINE_OEM5)
        .value("I2C_LINE_OEM6", ADLX_I2C_LINE::I2C_LINE_OEM6)
        .export_values();

    py::enum_<ADLX_HG_TYPE>(m, "ADLX_HG_TYPE")
        .value("NONE", ADLX_HG_TYPE::NONE)
        .value("AMD", ADLX_HG_TYPE::AMD)
        .value("OTHER", ADLX_HG_TYPE::OTHER)
        .export_values();
    
    py::enum_<ADLX_MEMORYTIMING_DESCRIPTION>(m, "ADLX_MEMORYTIMING_DESCRIPTION")
        .value("MEMORYTIMING_DEFAULT", ADLX_MEMORYTIMING_DESCRIPTION::MEMORYTIMING_DEFAULT)
        .value("MEMORYTIMING_FAST_TIMING", ADLX_MEMORYTIMING_DESCRIPTION::MEMORYTIMING_FAST_TIMING)
        .value("MEMORYTIMING_FAST_TIMING_LEVEL_2", ADLX_MEMORYTIMING_DESCRIPTION::MEMORYTIMING_FAST_TIMING_LEVEL_2)
        .value("MEMORYTIMING_AUTOMATIC", ADLX_MEMORYTIMING_DESCRIPTION::MEMORYTIMING_AUTOMATIC)
        .value("MEMORYTIMING_MEMORYTIMING_LEVEL_1", ADLX_MEMORYTIMING_DESCRIPTION::MEMORYTIMING_MEMORYTIMING_LEVEL_1)
        .value("MEMORYTIMING_MEMORYTIMING_LEVEL_2", ADLX_MEMORYTIMING_DESCRIPTION::MEMORYTIMING_MEMORYTIMING_LEVEL_2)
        .export_values();

    py::enum_<ADLX_GAMUT_SPACE>(m, "ADLX_GAMUT_SPACE")
        .value("GAMUT_SPACE_CCIR_709", ADLX_GAMUT_SPACE::GAMUT_SPACE_CCIR_709)
        .value("GAMUT_SPACE_CCIR_601", ADLX_GAMUT_SPACE::GAMUT_SPACE_CCIR_601)
        .value("GAMUT_SPACE_ADOBE_RGB", ADLX_GAMUT_SPACE::GAMUT_SPACE_ADOBE_RGB)
        .value("GAMUT_SPACE_CIE_RGB", ADLX_GAMUT_SPACE::GAMUT_SPACE_CIE_RGB)
        .value("GAMUT_SPACE_CCIR_2020", ADLX_GAMUT_SPACE::GAMUT_SPACE_CCIR_2020)
        .value("GAMUT_SPACE_CUSTOM", ADLX_GAMUT_SPACE::GAMUT_SPACE_CUSTOM)
        .export_values();

    //ADLX_WHITE_POINT
    py::enum_<ADLX_WHITE_POINT>(m, "ADLX_WHITE_POINT")
        .value("WHITE_POINT_5000K", ADLX_WHITE_POINT::WHITE_POINT_5000K)
        .value("WHITE_POINT_6500K", ADLX_WHITE_POINT::WHITE_POINT_6500K)
        .value("WHITE_POINT_7500K", ADLX_WHITE_POINT::WHITE_POINT_7500K)
        .value("WHITE_POINT_9300K", ADLX_WHITE_POINT::WHITE_POINT_9300K)
        .value("WHITE_POINT_CUSTOM", ADLX_WHITE_POINT::WHITE_POINT_CUSTOM)
        .export_values();

    //ADLX_SYNC_ORIGIN
    py::enum_<ADLX_SYNC_ORIGIN>(m, "ADLX_SYNC_ORIGIN")
        .value("SYNC_ORIGIN_UNKNOWN", ADLX_SYNC_ORIGIN::SYNC_ORIGIN_UNKNOWN)
        .value("SYNC_ORIGIN_INTERNAL", ADLX_SYNC_ORIGIN::SYNC_ORIGIN_INTERNAL)
        .value("SYNC_ORIGIN_EXTERNAL", ADLX_SYNC_ORIGIN::SYNC_ORIGIN_EXTERNAL)
        .export_values();

    //ADLX_ANTILAG_STATE
    py::enum_<ADLX_ANTILAG_STATE>(m, "ADLX_ANTILAG_STATE")
        .value("ANTILAG", ADLX_ANTILAG_STATE::ANTILAG)
        .value("ANTILAGNEXT", ADLX_ANTILAG_STATE::ANTILAGNEXT)
        .export_values();

    //ADLX_AFMF_ALGORITHM
    py::enum_<ADLX_AFMF_ALGORITHM>(m, "ADLX_AFMF_ALGORITHM")
        .value("AFMF_ALGORITHM_AUTO", ADLX_AFMF_ALGORITHM::AFMF_ALGORITHM_AUTO)
        .value("AFMF_ALGORITHM_ENHANCED", ADLX_AFMF_ALGORITHM::AFMF_ALGORITHM_ENHANCED)
        .value("AFMF_ALGORITHM_STANDARD", ADLX_AFMF_ALGORITHM::AFMF_ALGORITHM_STANDARD)
        .export_values();

    //ADLX_AFMF_SEARCH_MODE_TYPE
    py::enum_<ADLX_AFMF_SEARCH_MODE_TYPE>(m, "ADLX_AFMF_SEARCH_MODE_TYPE")
        .value("AFMF_SEARCH_MODE_AUTO", ADLX_AFMF_SEARCH_MODE_TYPE::AFMF_SEARCH_MODE_AUTO)
        .value("AFMF_SEARCH_MODE_STANDARD", ADLX_AFMF_SEARCH_MODE_TYPE::AFMF_SEARCH_MODE_STANDARD)
        .value("AFMF_SEARCH_MODE_HIGH", ADLX_AFMF_SEARCH_MODE_TYPE::AFMF_SEARCH_MODE_HIGH)
        .export_values();

    //ADLX_AFMF_FAST_MOTION_RESP
    py::enum_<ADLX_AFMF_FAST_MOTION_RESP>(m, "ADLX_AFMF_FAST_MOTION_RESP")
        .value("AFMF_RESP_REPEAT_FRAMES", ADLX_AFMF_FAST_MOTION_RESP::AFMF_RESP_REPEAT_FRAMES)
        .value("AFMF_RESP_BLENDED_FRAMES", ADLX_AFMF_FAST_MOTION_RESP::AFMF_RESP_BLENDED_FRAMES)
        .export_values();

    //ADLX_AFMF_PERFORMANCE_MODE_TYPE
    py::enum_<ADLX_AFMF_PERFORMANCE_MODE_TYPE>(m, "ADLX_AFMF_PERFORMANCE_MODE_TYPE")
        .value("AFMF_PERFORMANCE_MODE_AUTO", ADLX_AFMF_PERFORMANCE_MODE_TYPE::AFMF_PERFORMANCE_MODE_AUTO)
        .value("AFMF_PERFORMANCE_MODE_QUALITY", ADLX_AFMF_PERFORMANCE_MODE_TYPE::AFMF_PERFORMANCE_MODE_QUALITY)
        .value("AFMF_PERFORMANCE_MODE_PERFORMANCE", ADLX_AFMF_PERFORMANCE_MODE_TYPE::AFMF_PERFORMANCE_MODE_PERFORMANCE)
        .export_values();

    // ADLX_DP_LINK_RATE
    py::enum_<ADLX_DP_LINK_RATE>(m, "ADLX_DP_LINK_RATE")
        .value("DP_LINK_RATE_UNKNOWN", ADLX_DP_LINK_RATE::DP_LINK_RATE_UNKNOWN)
        .value("DP_LINK_RATE_RBR", ADLX_DP_LINK_RATE::DP_LINK_RATE_RBR)
        .value("DP_LINK_RATE_2_16GBPS", ADLX_DP_LINK_RATE::DP_LINK_RATE_2_16GBPS)
        .value("DP_LINK_RATE_2_43GBPS", ADLX_DP_LINK_RATE::DP_LINK_RATE_2_43GBPS)
        .value("DP_LINK_RATE_HBR", ADLX_DP_LINK_RATE::DP_LINK_RATE_HBR)
        .value("DP_LINK_RATE_4_32GBPS", ADLX_DP_LINK_RATE::DP_LINK_RATE_4_32GBPS)
        .value("DP_LINK_RATE_HBR2", ADLX_DP_LINK_RATE::DP_LINK_RATE_HBR2)
        .value("DP_LINK_RATE_HBR3", ADLX_DP_LINK_RATE::DP_LINK_RATE_HBR3)
        .value("DP_LINK_RATE_UHBR10", ADLX_DP_LINK_RATE::DP_LINK_RATE_UHBR10)
        .value("DP_LINK_RATE_UHBR13D5", ADLX_DP_LINK_RATE::DP_LINK_RATE_UHBR13D5)
        .value("DP_LINK_RATE_UHBR20", ADLX_DP_LINK_RATE::DP_LINK_RATE_UHBR20)
        .export_values();

    // ADLX_PCI_BUS_TYPE
    py::enum_<ADLX_PCI_BUS_TYPE>(m, "ADLX_PCI_BUS_TYPE")
        .value("UNDEFINED", ADLX_PCI_BUS_TYPE::UNDEFINED)
        .value("PCI", ADLX_PCI_BUS_TYPE::PCI)
        .value("AGP", ADLX_PCI_BUS_TYPE::AGP)
        .value("PCIE", ADLX_PCI_BUS_TYPE::PCIE)
        .value("PCIE_2_0", ADLX_PCI_BUS_TYPE::PCIE_2_0)
        .value("PCIE_3_0", ADLX_PCI_BUS_TYPE::PCIE_3_0)
        .value("PCIE_4_0", ADLX_PCI_BUS_TYPE::PCIE_4_0)
        .value("PCIE_5_0", ADLX_PCI_BUS_TYPE::PCIE_5_0)
        .export_values();

    // ADLX_MGPU_MODE
    py::enum_<ADLX_MGPU_MODE>(m, "ADLX_MGPU_MODE")
        .value("MGPU_NONE", ADLX_MGPU_MODE::MGPU_NONE)
        .value("MGPU_PRIMARY", ADLX_MGPU_MODE::MGPU_PRIMARY)
        .value("MGPU_SECONDARY", ADLX_MGPU_MODE::MGPU_SECONDARY)
        .export_values();

    // ADLX_APP_GPU_DEPENDENCY
    py::enum_<ADLX_APP_GPU_DEPENDENCY>(m, "ADLX_APP_GPU_DEPENDENCY")
        .value("APP_GPU_UNKNOWN", ADLX_APP_GPU_DEPENDENCY::APP_GPU_UNKNOWN)
        .value("APP_GPU_BOUND", ADLX_APP_GPU_DEPENDENCY::APP_GPU_BOUND)
        .value("APP_GPU_NOT_BOUND", ADLX_APP_GPU_DEPENDENCY::APP_GPU_NOT_BOUND)
        .export_values();

    // ADLX_SSM_BIAS_MODE
    py::enum_<ADLX_SSM_BIAS_MODE>(m, "ADLX_SSM_BIAS_MODE")
        .value("SSM_BIAS_AUTO", ADLX_SSM_BIAS_MODE::SSM_BIAS_AUTO)
        .value("SSM_BIAS_MANUAL", ADLX_SSM_BIAS_MODE::SSM_BIAS_MANUAL)
        .export_values();

    // ADLX_SMARTSHIFT_ECO_INACTIVE_REASON
    py::enum_<ADLX_SMARTSHIFT_ECO_INACTIVE_REASON>(m, "ADLX_SMARTSHIFT_ECO_INACTIVE_REASON")
        .value("INACTIVE_REASON_UNKNOWN", ADLX_SMARTSHIFT_ECO_INACTIVE_REASON::INACTIVE_REASON_UNKNOWN)
        .value("INACTIVE_REASON_PRIMARY_DISPLAY_CONNECTED_TO_DGPU", ADLX_SMARTSHIFT_ECO_INACTIVE_REASON::INACTIVE_REASON_PRIMARY_DISPLAY_CONNECTED_TO_DGPU)
        .value("INACTIVE_REASON_DETACHABLE_GPU_CONNECTED", ADLX_SMARTSHIFT_ECO_INACTIVE_REASON::INACTIVE_REASON_DETACHABLE_GPU_CONNECTED)
        .value("INACTIVE_REASON_SESSION_INACTIVE", ADLX_SMARTSHIFT_ECO_INACTIVE_REASON::INACTIVE_REASON_SESSION_INACTIVE)
        .value("INACTIVE_REASON_MULTIPLE_SESSION_ACTIVE", ADLX_SMARTSHIFT_ECO_INACTIVE_REASON::INACTIVE_REASON_MULTIPLE_SESSION_ACTIVE)
        .export_values();

    // ADLX_VARIABLE_GRAPHICS_MEMORY_MODE
    py::enum_<ADLX_VARIABLE_GRAPHICS_MEMORY_MODE>(m, "ADLX_VARIABLE_GRAPHICS_MEMORY_MODE")
        .value("VARIABLE_GRAPHICS_MEMORY_MODE_AUTO", ADLX_VARIABLE_GRAPHICS_MEMORY_MODE::VARIABLE_GRAPHICS_MEMORY_MODE_AUTO)
        .value("VARIABLE_GRAPHICS_MEMORY_MODE_CUSTOM", ADLX_VARIABLE_GRAPHICS_MEMORY_MODE::VARIABLE_GRAPHICS_MEMORY_MODE_CUSTOM)
        .export_values();
}
