[package]
name = "three-d-settings-event"
description = "ADLX Rust sample: handle notifications about 3D settings changes"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "3DSettingsEvent"
path = "src/main.rs"

[dependencies]
amd-adlx = { path = "../amd-adlx" }
